### ISSUE TITLE
handleAuthentication doesn't accept arguments

### ISSUE THREAD

**Issue by a-kinder** [auth0-samples/auth0-react-samples#10]
Trying to implement the react quickstart, granted in typescript so that may be the issue, but it looks like in [routes.js](https://github.com/auth0-samples/auth0-react-samples/blob/802550e0c6a23db9206e099d0edfe8fa7b8fe855/01-Login/src/routes.js#L13) it is calling handleAuthentication with an argument: 

`auth.handleAuthentication(nextState.location.hash);`

but in [Auth.js](https://github.com/auth0-samples/auth0-react-samples/blob/d7d51a8699c081958851cbd6bee08a60a64b7879/01-Login/src/Auth/Auth.js#L28) there is no argument. It looks like maybe `err, authResult` should be passed in and then forward to parseHash. Is this correct?

**Comment by chenkie** [comment]
Looks like it's passed unnecessarily. Thanks for the heads up, I'll put in the fix :)
