### ISSUE TITLE
This resource is no longer available under v1 APIs

### ISSUE THREAD

**Issue by webmobiles** [auth0-samples/auth0-react-samples#102]
I'm using: 
cd 02-User-Profile
npm install
* I've setted the parameters for linkedin keys, and finally:
npm start

After try login with linkedin, and accept, i get this error:

```
error
:
"invalid_request"
errorDescription
:
"InternalOAuthError: failed to fetch user profile (status: 410 data: {↵  "errorCode": 0,↵  "message": "This resource is no longer available under v1 APIs",↵  "requestId": "C882QYSQU7",↵  "status": 410,↵  "timestamp": 1546006660054↵})"
state
:
"1EIiEDxwof9ongtHEv89vKus0ahJF8Ju"

  "errorCode": 0,
  "message": "This resource is no longer available under v1 APIs",
  "requestId": "C882QYSQU7",
  "status": 410,
  "timestamp": 1546006660054
})"
```

there is a problem with the version, it's needed to update some packages?

**Comment by jimmyjames** [comment]
I think that error is related to trying to use v1 of the LinkedIn API, which is now deprecated. When you set up your LinkedIn connection, try changing to Version 2 like this: 

<img width="610" alt="Screen Shot 2019-06-24 at 2 58 53 PM" src="https://user-images.githubusercontent.com/276225/60047995-bce39800-9690-11e9-947b-5e64ae448bd2.png">

If you continue to experience any issues, please reopen and provide additional information, including any additional changes to the sample code that you've made. Thanks!
