### ISSUE TITLE
05-Token-Renewal Error: clientID option is required

### ISSUE THREAD

**Issue by fabianbaier** [auth0-samples/auth0-react-samples#105]
Hi,

Running a fresh git clone of `auth0-samples/auth0-react-samples` brings the following error message when running `npm run start` after `npm install` in folder `05-Token-Renewal`:

```
Error: clientID option is required
▶ 3 stack frames were collapsed.
new Auth
src/github.com/auth0-samples/auth0-react-samples/05-Token-Renewal/src/Auth/Auth.js:20
  17 |   scope: 'openid profile'
  18 | });
  19 | 
> 20 | constructor() {
     | ^  21 |   this.login = this.login.bind(this);
  22 |   this.logout = this.logout.bind(this);
  23 |   this.handleAuthentication = this.handleAuthentication.bind(this);
```

Same behavior when running the `exec.sh` and its docker image.

Also, when logged in to Auth0 there is a suggestion of using https://github.com/auth0/docs/tree/master/articles/quickstart/spa/react won't work either and seems to be outdated. 

Ideas?

**Comment by Alevale** [comment]
This is fixed by https://github.com/auth0-samples/auth0-react-samples/pull/120 it's just a typo

**Comment by elkdanger** [comment]
@fabianbaier This issue should now be resolved. If you're still experiencing problems, please feel free to re-open or raise another issue.

**Comment by lopeselio** [comment]
It is just a typo: 

You can resolve this by changing 'clientId'  to 'clientID'
