### ISSUE TITLE
Element type is invalid: when routes(named import) are passed to reactDOM.render() method.

### ISSUE THREAD

**Issue by abidabdelaziz** [auth0-samples/auth0-react-samples#106]
//package.json
```

{ "name": "storefront",
      "version": "0.1.0",
      "private": true,
      "dependencies": {
        "auth0-js": "^9.10.0",
        "react": "^16.7.0",
        "react-bootstrap": "^1.0.0-beta.5",
        "react-dom": "^16.7.0",
        "react-router": "^4.3.1",
        "react-router-dom": "^4.3.1",
        "react-scripts": "2.1.3"
      },
      "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject"
      },
      "eslintConfig": {
        "extends": "react-app"
      },
      "browserslist": [
        ">0.2%",
        "not dead",
        "not ie <= 11",
        "not op_mini all"
      ]
    }
```
//index.js

```
import  ReactDOM  from 'react-dom';
import React from 'react';
import  { makeMainRoutes }  from './routes';

const routes = makeMainRoutes();
ReactDOM.render(
  routes,
  document.getElementById('root')
);
```
//routes.js

```
import React from 'react';
import { Route, Switch, BrowserRouter as Router } from 'react-router-dom';
import App from './App';
import Home from './Home/Home';
import Callback from './Callback/Callback';
import Auth from './Auth/Auth';
import history from './history';

const auth = new Auth();

const handleAuthentication = (nextState, replace) => {
  if (/access_token|id_token|error/.test(nextState.location.hash)) {
    auth.handleAuthentication();
  }
}

export const makeMainRoutes = () => {
    return (
    <Router history={history} component={App}>
      <Switch>
        <Route path="/" render={(props) => <App auth={auth} {...props} />} />
        <Route path="/home" render={(props) => <Home auth={auth} {...props} />} />
        <Route path="/callback" render={(props) => {
          handleAuthentication(props);
          return <Callback {...props} /> 
        }}/>
      </Switch>
    </Router>
  );
}
```
//App.js
```
import React, { Component } from 'react';
import { Navbar, Button } from 'react-bootstrap';


// const auth = new Auth();


export default  class App extends Component {
  goTo(route) {
    this.props.history.replace(`/${route}`)
  }

  login() {
    this.props.auth.login();
  }

  logout() {
    this.props.auth.logout();
  }

  componentDidMount() {
    const { renewSession } = this.props.auth;

    if (localStorage.getItem('isLoggedIn') === 'true') {
      renewSession();
    }
  }

  render() {
     const { isAuthenticated } = this.props.auth

    return (
      <div>
        <Navbar fluid>
          <Navbar.Header>
            <Navbar.Brand>
              <a href="/">Auth0 - React</a>
            </Navbar.Brand>
            <Button
              bsStyle="primary"
              className="btn-margin"
              onClick={this.goTo.bind(this, 'home')}
            >
              Home
            </Button>
            {
              !isAuthenticated() && (
                  <Button
                    bsStyle="primary"
                    className="btn-margin"
                    onClick={this.login.bind(this)}
                  >
                    Log In
                  </Button>
                )
            }
            {
              isAuthenticated() && (
                  <Button
                    bsStyle="primary"
                    className="btn-margin"
                    onClick={this.logout.bind(this)}
                  >
                    Log Out
                  </Button>
                )
            }
          </Navbar.Header>
        </Navbar>
      </div>
    );
  }
}
```
//error

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
▶ 28 stack frames were collapsed.
Module../src/index.js
C:/Users/Alexander/Desktop/Code/StoreFront/storeFront/storefront/src/index.js:6
  3 | import  { makeMainRoutes }  from './routes';
  4 | 
  5 | const routes = makeMainRoutes();
> 6 | ReactDOM.render(
  7 |   routes,
  8 |   document.getElementById('root')
  9 | );
As I understand it there is an issue with what TYPE routes is. makeMainRoutes is a function which returns JSX markup for the routing component. I'm importing it in index.js and declaring a new instance of that function and then passing it the render method of reactDOM. Is there a flaw in my understanding? Thank you so much! I feel like I'm at my wits end.

**Comment by abidabdelaziz** [comment]
I think the issue is this

  `"react-bootstrap": "^1.0.0-beta.5"` 

making the following changes to the NavBar component resolved the error
`<Navbar >

         
         
            <Navbar.Brand>
              <a href="/">Store Front</a>
            </Navbar.Brand>
            <Button
          
              className="btn-margin"
              onClick={this.goTo.bind(this, 'home')}
            >
              Home
            </Button>
            {
              !isAuthenticated() && (
                  <Button
                   
                    className="btn-margin"
                    onClick={this.login.bind(this)}
                  >
                    Log In
                  </Button>
                )
            }
            {
              isAuthenticated() && (
                  <Button
                    
                    className="btn-margin"
                    onClick={this.logout.bind(this)}
                  >
                    Log Out
                  </Button>
                )
            }
      
        </Navbar>`

errors where thrown  @

 ```
<Navbar fluid>
          <Navbar.Header>
```
and @ 

` bsStyle="primary"`

the only outstanding issue so far that I can find in the sample log-in tutorial is this

`Uncaught SyntaxError: Unexpected token < auth0.js:1
`

**Comment by abidabdelaziz** [comment]
I'm left with this when I try to login with google.

```
auth0.min.esm.js:8 GET https://storefrontmvp.auth0.com/user/ssodata 404

lock.min.js:9 [Violation] 'setTimeout' handler took 105ms

index.js:410 There was an error fetching the SSO data. This could simply mean that there was a problem with the network. But, if a "Origin" error has been logged before this warning, please add...

GET https://secure.gravatar.com/avatar/860749f6372a350c9054770607c5a8de?d=404&s=160 404

GET https://secure.gravatar.com/860749f6372a350c9054770607c5a8de.json?callback=__jp0 net::ERR_ABORTED 404

Navigated to http://localhost:3000/callback
```

**Comment by MattHartz** [comment]
Any answers to this @abidabdelaziz ?

**Comment by jimmyjames** [comment]
Closing this issue  since we've just recently made some significant changes to this sample and Quickstart, utilizing the new `auth0-spa-js` SDK. If you continue to experience this issue or any others, don't hesitate to create a new issue. Thanks!

References:
- [Updated React Quickstart](https://auth0.com/docs/quickstart/spa/react)
- [auth0-spa-js SDK](https://github.com/auth0/auth0-spa-js)
