### ISSUE TITLE
React-Login Example: callbackUrl hard coded in routes.js

### ISSUE THREAD

**Issue by maboud** [auth0-samples/auth0-react-samples#107]
In routes.js the path for the callback is hard coded as "/callback", and doesn't make use of the callbackUrl defined in auth0-variables.js; hence the example only works if the callback path is "/callback"

```
<Route path="/callback" render={(props) => {
            handleAuthentication(props);
            return <Callback {...props} /> 
          }}/>
```

**Comment by stevehobbsdev** [comment]
@maboud The samples have since been updated and `callbackUrl` is no longer specified in the configuration file. Apologies for the length of time it has taken to get back to you.
