### ISSUE TITLE
Why subclass EventEmitter?

### ISSUE THREAD

**Issue by davidascher** [auth0-samples/auth0-react-samples#12]
It's not clear to me from the code in `Auth.js` that it's using the subclassing of `EventEmitter` -- could it be that's not needed anymore?  If so, happy to provide a PR to remove it and the dependency.

**Comment by chenkie** [comment]
Looks like it's a carry-over from older samples. If you're up for making the changes that would be great :)

Thanks

**Comment by davidascher** [comment]
ah, sorry, this dropped off my radar.

**Comment by chenkie** [comment]
No prob! :)
