### ISSUE TITLE
Invalid = token in class

### ISSUE THREAD

**Issue by valecarlos** [auth0-samples/auth0-react-samples#13]
running the current Auth.js gives me the following error when not using this whole project based on create-react-app.

`ERROR in ./app/Auth/Auth.js
Module build failed: SyntaxError: C:/Users/carlos.valencia/Documents/POCs/cux-tester-app/app/Auth/Auth.js: Unexpected token (4:11)

  2 |
  3 | export default class Auth {
> 4 |      auth0 = new auth0.WebAuth({
    |            ^
  5 |         domain: ...`

As far as i know that is not valid ES2015 syntax, how do you get this to work?

**Comment by chenkie** [comment]
hey there

can you clarify what you mean by this line? 

> when not using this whole project based on create-react-app.

**Comment by Sam-Houlahan** [comment]
same problem here.

**Comment by chenkie** [comment]
Can you confirm whether you get this if you run this sample out of the box? Or is it happening when porting to your own project?

**Comment by Sam-Houlahan** [comment]
porting to own project

**Comment by chenkie** [comment]
ok thanks. are you using create-react-app? if not, what's your build setup like? I'm trying to determine what might be causing issues with other systems since it works ok with create-react-app.

**Comment by jongamble** [comment]
I had the same issue with our builds. We were using webpack and babel. Our solution was adding the `stage-0` preset to babel.

**Comment by valecarlos** [comment]
@jongamble Thanks, adding `presets: ['stage-0']` to the `options `along with the `babel-loader` on the webpack.config.js does resolve this issue.
