### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by blakedietz** [auth0-samples/auth0-react-samples#134]
## Type of report

- [x] Bug
- [ ] Feature request
- [ ] Discussion

## Description

Maybe I'm doing something boneheaded, but I've run into a problem with your quickstart both purely using your example and also in the application that I was trying to retrofit your source into.

## Experience

First I tried using your hook and wrapper from the example in my application and I ran into similar issues. From there I tried simplifying the problem to verify it wasn't my codebase or my machine and just used your example. This happens for both examples in your app.

## Steps to reproduce

- Clone this repo
- cd 02-Calling-an-API
- configure your ./src/auth_config.json as mentioned in the docs
- rm -rf node_modules yarn.lock;
- yarn;
- yarn start;
- log in to the app
- refresh the page

## Expected result

I can log in and log out of the application no problem. No errors are thrown.

## Actual result

Logging in doesn't seem to work immediately, only after an extended period waiting for a new refresh token. I log in via the auth0 dash and then get redirected to the application where the app hangs loading until the next token refresh is sent by the wrapper code in your example. Once the token refresh is done, then it works.

### Console

authorize.js is throwing a 400

**Comment by stevehobbsdev** [comment]
@blakedietz This is usually down to a configuration problem. If you check the network tab, you might see the call out to `/authorize` on `<your auth0 tenent>.auth0.com` failing, and there might be an HTTP response in there from Auth0 which may give you a clue as to the failure.

If that doesn't give you much info, you can also check the logs in your Auth0 dashboard, which may have registered an error when trying to authorize.

Let me know if you find anything useful.

**Comment by blakedietz** [comment]
Okay, you caught me. I didn't have my origin setup. 🤦‍♂

**Comment by stevehobbsdev** [comment]
No worries @blakedietz, glad you got it sorted!
