### ISSUE TITLE
Requires updated advanced oauth settings from HS-256 to RS-256

### ISSUE THREAD

**Issue by justin-dunham** [auth0-samples/auth0-react-samples#136]
Working through the React.js SPA example and I was getting this console error on Google Sign-up or Login. 

![Screen Shot 2019-07-08 at 11 55 03 AM](https://user-images.githubusercontent.com/43351446/60826063-1791ef00-a17b-11e9-9894-4ca84275bc38.png)

I was able to track down the exception in [auth0-spa-js](https://github.com/auth0/auth0-spa-js/blob/master/src/jwt.ts#L65) 

I was able to work around by updating advanced settings from HS-256 to RS-256. This should be documented or if possible the default value updated.

**Comment by stevehobbsdev** [comment]
Thanks for raising this @justin-dunham. You're right in that the SPA SDK only supports RS256 and is the more secure option. Which documentation were you working through, or have you been looking at this sample repo in isolation? Also, were you using an old Auth0 app to test your sample with?

The default when you create a new Auth0 app is RS256, but we could be better at explaining the setup. I've raised something internally to improve the docs in this area.

**Comment by Rukaan** [comment]
I got the same error today when following this [guide](https://auth0.com/docs/quickstart/spa/react#introduction)

I also tried to login with google and normal login

**Comment by stevehobbsdev** [comment]
@Rukaan Sometimes the Default App can be a little funky; glad you got it sorted though.

**Comment by justin-dunham** [comment]
@Rukaan I also used the default app when setting things up so maybe that was the issue.

**Comment by luisrudge** [comment]
Thanks for reporting this. We added this to our FAQ section here: https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-an-invalid-algorithm-error
