### ISSUE TITLE
Sample 01-Login not working

### ISSUE THREAD

**Issue by Oxyrus** [auth0-samples/auth0-react-samples#141]
Currently the login functionality doesn't seem to work on a fresh setup.

After setting up my `domain` and `clientId` in the `auth_config.json` file and logging in, the application gets stuck indefinitely in the callback (see screenshot).

![image](https://user-images.githubusercontent.com/11398826/61165516-5f03dc80-a4e7-11e9-9092-65f53c70aa43.png)

The console shows the following error:

> Uncaught (in promise) Error: Invalid algorithm
>    at re (auth0-spa-js.production.js:710)
>    at ie._verifyIdToken (auth0-spa-js.production.js:764)
>    at ie.<anonymous> (auth0-spa-js.production.js:877)
>    at Generator.next (<anonymous>)
>    at a (auth0-spa-js.production.js:26)

But the error is unclear, so I'm not sure of what's happening.

**Comment by lbalmaceda** [comment]
Hey @Oxyrus , I see this is documented in the library's FAQ. https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-an-invalid-algorithm-error. Can you please try that?

**Comment by Oxyrus** [comment]
That was it, thanks a lot @lbalmaceda !

Might I suggest adding it to the README of the samples as well?

**Comment by lbalmaceda** [comment]
@stevehobbsdev how do you suggest we proceed here, maybe link to the FAQ from the quickstart article?
