### ISSUE TITLE
React hooks + @apollo/hooks

### ISSUE THREAD

**Issue by nojaf** [auth0-samples/auth0-react-samples#142]
Hi, how would the[ React wrapper](https://auth0.com/docs/quickstart/spa/react/#install-the-auth0-react-wrapper) work in combination with [@apollo/hooks](https://www.npmjs.com/package/@apollo/react-hooks)?

At some point in my application, I would like to add an additional header with my access token if the user decided to log in. Some graphql queries should be available when the user isn't logged in.
So I have a scenario where I want to add the header only at a later point.

More to the point, consider the following code:

```js
import { ApolloClient } from "apollo-client";
import { HttpLink } from "apollo-link-http";
import { setContext } from "apollo-link-context";
import { InMemoryCache } from "apollo-cache-inmemory";

const setAuthorizationLink = setContext((request, previousContext) => {
  // get hook??
  // get accessToken somehow???
  return {
    headers: { authorization: "1234" }
  };
});

export function createApolloClient() {
  const httpLink = new HttpLink({
    uri: "/api/graphql"
  });

  const link = setAuthorizationLink.concat(httpLink);

  return new ApolloClient({
    link,
    cache: new InMemoryCache()
  });
}
```

How do I get my bearer token inside the setContext callback?

**Comment by luisrudge** [comment]
@nojaf keep in mind that the react wrapper is not required to use the SDK with react. If you can't use hooks because you're not rendering inside a component, then you should absolutely use the SDK alone: https://github.com/auth0/auth0-spa-js#2---calling-an-api. There's no docs on apollo with hooks yet, but I think the setup is the same, so I think your best bet is to use the regular SDK to fulfill your needs. Perhaps modify the react wrapper to accept an instance of the Auth0Client that was already initialized etc. What do you think?

**Comment by nojaf** [comment]
Having an instance outside the hooks setup sounds indeed like the way to go.
Could you give me a pointer how that would work if want to pass an instance [in the wrapper](https://auth0.com/docs/quickstart/spa/react/#install-the-auth0-react-wrapper)?

Because if the auth0 client is being passed as a prop, I don't think that is going to work out.
Similar to what I've encountered in https://github.com/auth0/auth0-spa-js/issues/50

**Comment by luisrudge** [comment]
I think you can pass it as a prop to the provider and just set it as the default state.

**this is untested code**

```js
export const Auth0Provider = ({
  children,
  auth0Client,
  onRedirectCallback = DEFAULT_REDIRECT_CALLBACK,
  ...initOptions
}) => {
  const [isAuthenticated, setIsAuthenticated] = useState();
  const [user, setUser] = useState();
  const [auth0Client, setAuth0] = useState(auth0Client);
  const [loading, setLoading] = useState(true);
  const [popupOpen, setPopupOpen] = useState(false);

  useEffect(() => {
    const initAuth0 = async () => {
      let auth0FromHook = auth0Client;
      if (!auth0FromHook) {
        auth0FromHook = await createAuth0Client(initOptions);
        setAuth0(auth0FromHook);
      }

      if (window.location.search.includes("code=")) {
        const { appState } = await auth0FromHook.handleRedirectCallback();
        onRedirectCallback(appState);
      }

      const isAuthenticated = await auth0FromHook.isAuthenticated();

      setIsAuthenticated(isAuthenticated);

      if (isAuthenticated) {
        const user = await auth0FromHook.getUser();
        setUser(user);
      }

      setLoading(false);
    };
    initAuth0();
    // eslint-disable-next-line
  }, []);

  const loginWithPopup = async (params = {}) => {
    setPopupOpen(true);
    try {
      await auth0Client.loginWithPopup(params);
    } catch (error) {
      console.error(error);
    } finally {
      setPopupOpen(false);
    }
    const user = await auth0Client.getUser();
    setUser(user);
    setIsAuthenticated(true);
  };

  const handleRedirectCallback = async () => {
    setLoading(true);
    await auth0Client.handleRedirectCallback();
    const user = await auth0Client.getUser();
    setLoading(false);
    setIsAuthenticated(true);
    setUser(user);
  };
  return (
    <Auth0Context.Provider
      value={{
        isAuthenticated,
        user,
        loading,
        popupOpen,
        loginWithPopup,
        handleRedirectCallback,
        getIdTokenClaims: (...p) => auth0Client.getIdTokenClaims(...p),
        loginWithRedirect: (...p) => auth0Client.loginWithRedirect(...p),
        getTokenSilently: (...p) => auth0Client.getTokenSilently(...p),
        getTokenWithPopup: (...p) => auth0Client.getTokenWithPopup(...p),
        logout: (...p) => auth0Client.logout(...p)
      }}
    >
      {children}
    </Auth0Context.Provider>
  );
};
```

**Comment by nojaf** [comment]
Found another way:
```js
import { Auth0Provider } from "./react-auth0-wrapper.js"
import { ApolloProvider } from "@apollo/react-hooks";
import { createApolloClient } from "./helper.js";

const ApolloWrapper = ({children}) => {
   const { getTokenSilently, loading  = useAuth0();
   const apolloClient = useMemo(() => createApolloClient(getTokenSilently), [loading]);
   return <ApolloProvider client={apolloClient>{children</ApolloProvider>
}

const App = () => {
   return <Auth0Provider {...}>
        <ApolloWrapper><h1>my app</h1></ApolloWrapper>
    </Auth0Provider >
}
```

helper.js
```js
import { ApolloClient } from "apollo-client";
import { HttpLink } from "apollo-link-http";
import { setContext } from "apollo-link-context";
import { InMemoryCache } from "apollo-cache-inmemory";

export function createApolloClient(getToken) {
  const httpLink = new HttpLink({
    uri: "/api/graphql"
  });

  const setAuthorizationLink = setContext((_, { headers }) => {
    return getToken().then(token => {
      debugger;
      console.log(`TOKEN:${token}`);
      return {
        headers: {
          ...headers,
          authorization: token ? `Bearer ${token}` : null
        }
      }
    });
  });

  const link = setAuthorizationLink.concat(httpLink);

  return new ApolloClient({
    link,
    cache: new InMemoryCache()
  });
}

```

**Comment by luisrudge** [comment]
@nojaf amazing! I didn't know you could provide a function to the `client` prop. Thanks for following this up!

**Comment by nirvdrum** [comment]
@nojaf I've tried out [your solution](https://github.com/auth0-samples/auth0-react-samples/issues/142#issuecomment-511497830), but it's not working and I don't see how it can. I believe it did work for you, so I'm not sure if I'm just overlooking something or if the SPA React wrapper changed. Any help you can provide would be much appreciated.

The problem is the `getTokenSilently` reference is invalid while Auth0 `loading` is `true` because the `auth0Client` reference is `undefined` until `loading` is `false`. Just to be clear that we're looking at the same thing, I'm referring to the the provider's `getTokenSilently` value, like in https://github.com/auth0-samples/auth0-react-samples/issues/142#issuecomment-511470797.

So, I'm uncertain how the `useMemo` call you have can work. Did you update the wrapper so that the provider always passes down a Promise for `getTokenSilently`?

**Comment by Lukasvo** [comment]
@nirvdrum I'm having the exact same issue with this solution.
The thing is, everything seems to work once `loading` turns to `false`. The only side effect I have is a console error that says `Cannot read property 'getTokenSilently' of undefined`

**Comment by NikitaVr** [comment]
I was having the `undefined` problem recently, but noticed that they changed `getTokenSilently` to `getAccessTokenSilently` in the newer versions
