### ISSUE TITLE
Retrieve email from token | @auth0/auth0-spa-js

### ISSUE THREAD

**Issue by bexuma** [auth0-samples/auth0-react-samples#144]
I have been trying to upgrade to **@auth0/auth0-spa-js** from **auth0-js**, although I could not get my head around retrieving an email property from a token which in turn was obtained from `await useAuth0().getTokenSilently()`

I use [jwt.io](https://jwt.io/) to decrypt the token, and this is what I get in the payload:

```
{
  "iss": "https://TENANT_NAME.auth0.com/",
  "sub": "auth0|SOME_HASH",
  "aud": [
    "https://API_IDENTIFIER",
    "https://TENANT_NAME.auth0.com/userinfo"
  ],
  "iat": 1563699940,
  "exp": 1563786340,
  "azp": "SOME_OTHER_HASH",
  "scope": "openid profile email"
}
```

When I was using **auth0-js** I could just add `scope: "openid email"` to `new auth0.WebAuth({...})` and voilà – I had **email** and **email_verified** in the payload of the decrypted token.

I believe the [2 part series of tutorials](https://auth0.com/docs/quickstart/spa/react/) were not able to answer my question, and reading the token from a hooked `getTokenSilently()` inside my Apollo configuration was also a challenge on its own. I like the redirect implementation for SPA, however. Please, can you suggest a proper way to include email and email_verified to the token's payload?

**Comment by bexuma** [comment]
By reading [this article](https://auth0.com/docs/api-auth/tutorials/adoption/api-tokens) I understood the token I am getting is called **the access token**. I have been using ID tokens in the header of my requests till this day, and that is probably a bad approach:

> In the OIDC-conformant pipeline, ID Tokens should never be used as API tokens.

Also, the documentation says:

> The token **does not contain** any information about the user except for the user ID (located in the sub claim).

> In many cases, you may find it useful to retrieve additional user information. You can do this by calling the /userinfo API endpoint with the Access Token.

Which I did by following [shell example](https://auth0.com/docs/api/authentication?javascript#get-user-info). I have sent the request with my access token and magically got an object containing the user's profile information.

We got close, what is an algorithm converting the "sub" into user profile for my backend in ruby?

**Comment by luisrudge** [comment]
I'm sorry you feel kinda lost right now. We're still working out on our auth0-js migration guide, so we can show various before/after scenarios and make this migration easier.

In the mean time, I'd suggest you to take a look at our [documentation](https://auth0.com/docs/libraries/auth0-spa-js) that has all the information you need to:
- [get an access token to call an api](https://auth0.com/docs/libraries/auth0-spa-js#get-access-token-with-no-interaction)
- [get the authenticated user information without doing an extra http request to `/userinfo`](https://auth0.com/docs/libraries/auth0-spa-js#get-user)

If you have any questions, feel free to reach out to https://community.auth0.com so we can better assist you!
