### ISSUE TITLE
So, how do we handle refresh?

### ISSUE THREAD

**Issue by lucax88x** [auth0-samples/auth0-react-samples#146]
Ehi guys, I've been using auth0 in the past, and there was a time that after the redirect you would just read the hash and store tokens in local storage, but it seems it's no more the right way to do that:

ex: https://github.com/auth0-samples/auth0-react-samples/issues/98

So, my question is, where do I keep my tokens? 

The only way I actually found is to call the getTokenSilently everytime the page refreshes, and if this one fails then I assume user is not logged in, which would make sense.. is this the correct way?

**Comment by luisrudge** [comment]
Using the new SDK, you don't need to store your tokens anywhere. Just call `getTokenSilently` and you'll always get either a valid token or an error with the code `login_required`. If you get the token, perfect. If you get the error, then you need to call one of the `loginWith*` methods to login again. You can also call `isAuthenticated` before calling `getTokenSilently` if you don’t want to use try/catch.

**Comment by lucax88x** [comment]
@luisrudge 

After I did a successfull login with google account (using loginWithPopup), when I try to refresth the page, the getTokenSilently always fail with the "login_required", what I am doing wrong?

this is the code which run when the SPA starts

![image](https://user-images.githubusercontent.com/6294464/61716543-af88fe80-ad5f-11e9-9d23-5921a768174b.png)

**Comment by luisrudge** [comment]
Can you check if this helps? https://github.com/auth0/auth0-spa-js/issues/105#issuecomment-514190797

**Comment by lucax88x** [comment]
Yeah, it worked... you should (imho) disable the google login by default, this was a bit misleading, thanks!

**Comment by albertoperdomo** [comment]
@lucax88x In the New Universal Login experience this limitation is no longer present. As developers adopt it they are less likely to encounter this issue.

It seems there is a gap in our documentation where we describe those limitations since they only apply to the classic Universal Login experience.
