### ISSUE TITLE
Lost session on refresh page

### ISSUE THREAD

**Issue by abrahamgnz** [auth0-samples/auth0-react-samples#147]
Hi I'm trying the Login example, but each time I refresh the page the session is lost. Is this the intended behavior?

**Comment by abrahamgnz** [comment]
https://github.com/auth0-samples/auth0-react-samples/issues/146

**Comment by zhil** [comment]
@abrahamgnz did you fixed this issue?
looks like current sources not working - I got error "Failed to load resource: the server responded with a status of 400 ()" after page reload

**Comment by zhil** [comment]
@abrahamgnz sorry for annoying, but did you founded solution for this issue?
