### ISSUE TITLE
How are nested routes handled?

### ISSUE THREAD

**Issue by aust** [auth0-samples/auth0-react-samples#149]
What's the best practice for handling nested private sub routes? In this case, if you were to go to /dashboard/page1, since dashboard itself is private, it will authenticate at /dashboard and onRedirect will be at /dashboard instead of the targeted /dashboard/page1.

For example:

```
export const App = () => {
  const { loading } = useAuth0();

  if (loading) {
    return <span>Loading ...</span>;
  }

  return (
    <Router>
      <Switch>
        <PrivateRoute
          component={Dashboard}
          path="/dashboard"
        />
        <Route component={NotFound} />
      </Switch>
    </Router>
  );
};
```

`Dashboard` contains additional sub routes:

```
export const Dashboard = (props) => {
  return (
    {/* These routes could be wrapped in a shared header/footer */}
    <>
        <PrivateRoute exact path={`${props.match.path}/page1`} component={Page1} />
        <PrivateRoute exact path={`${props.match.path}/page2`} component={Page2} />
        <PrivateRoute exact path={`${props.match.path}/page3`} component={Page3} />
    </>
  );
};
```

The reasoning for this is that some users might not have access to each individual page based on their permissions (which is set in the Authentication Extension). I added additional functionality on `PrivateRoute` to also check the user's permissions via a permissions prop (not shown above).

**Comment by luisrudge** [comment]
If you hit /dashboard/page1 directly from the browser bar, the page that will redirect to /authorize will be /dashboard/page1. https://github.com/auth0-samples/auth0-react-samples/blob/master/01-Login/src/components/PrivateRoute.js#L13 `path` here will be the full path your trying to access, not the first route that matched the router.

**Comment by aust** [comment]
In this case it doesn't happen. The first route that's hit is /dashboard which will redirect to /authorize before /dashboard/page1.

**Comment by luisrudge** [comment]
are you saying that your /dashboard route is redirecting to /dashboard/page1?

**Comment by aust** [comment]
Here's the layout of my routes:

```
/dashboard
- /dashboard/page1
- /dashboard/page2
- /dashboard/page3
```

All 3 pages are exclusively rendered inside the dashboard wrapper.

If I enter `/dashboard/page1` into my address bar and hit enter, the first route that gets resolved is `/dashboard`. Authentication at this point has not been completed, so it redirects using `path` from the `/dashboard` route. I am now on `/dashboard` instead of my targeted `/dashboard/page1` route.

**Comment by luisrudge** [comment]
instead of using path, maybe you can try using `window.location.path` instead?

**Comment by aust** [comment]
Yes, that fixes a portion of it. The other issue is that both routes match and redirect to `/authorize`.

I think I shouldn't nest `PrivateRoute` since the parent (`/dashboard`) is already private. I was more or less using `PrivateRoute` to also check the permissions of the user.

Since I am nesting routes, I do still need to use `window.location.pathname` as the targetUrl since using `path` will always take me to the root route.

**Comment by luisrudge** [comment]
Ahhhhhh, gotcha! Yeah, if your top route already checks for authentication, there's no need to make the child routes PrivateRoute's as well. Maybe you can improve the PrivateRoute to support your scenario like this:

```
export const App = () => {
  const { loading } = useAuth0();

  if (loading) {
    return <span>Loading ...</span>;
  }

  return (
    <Router>
      <Switch>
        <PrivateRoute
          parent
          component={Dashboard}
          path="/dashboard"
        />
        <Route component={NotFound} />
      </Switch>
    </Router>
  );
};
```

```
const PrivateRoute = ({ parent, component: Component, path, ...rest }) => {
  const { isAuthenticated, loginWithRedirect } = useAuth0();

  useEffect(() => {
    const fn = async () => {
      if (!isAuthenticated && parent) {
        await loginWithRedirect({
          appState: { targetUrl: path }
        });
      }
    };
    fn();
  }, [isAuthenticated, loginWithRedirect, path]);

  const render = props =>
    isAuthenticated === true ? <Component {...props} /> : null;

  return <Route path={path} render={render} {...rest} />;
};
```

Notice I added a `parent` prop and that the redirect is only triggered when that prop is `true`. You can keep the logic you have to check for permissions etc.

Personally, I'd create two different components. One for Authentication (PrivateRoute - checks if the user is authenticated or not) and another one for Authorization (PermissionedRoute or something - here you'd only check for permissions). This way your logic is always contained in that specific component and you can manage when to use one or the other more  easily.
