### ISSUE TITLE
The user in Auth0Provider doesn't include metadata.

### ISSUE THREAD

**Issue by groffcole** [auth0-samples/auth0-react-samples#156]
I want to be able to restrict routes based on a user's role. For example, I'd like to have an admin page that only admins can access. In the current implementation the `PrivateRoute` only restricts users if they aren't authenticated. 

I have a user that has a role using the Authorization Core stuff. My Auth0 api returns JWTs with permissions from the user's assigned role. But what if I just wanted to check the user's role and NOT decode the JWT on the client side to check individual permissions? Is it possible to get at a user's roles from the `user` in the `Auth0Context` returned from `Auth0Provider`?

If that isn't possible, is it safe to decode the user's JWT on the client-side to check individual permissions?

I just need a little guidance - thanks.

**Comment by luisrudge** [comment]
We had a lengthy discussion over this same topic in our repo: https://github.com/auth0/auth0-spa-js/issues/23#issuecomment-507794605.
There's some good pointers in that issue that will help you find the best solution to do what you want.
