### ISSUE TITLE
Making callApi a global/utils function 

### ISSUE THREAD

**Issue by Alon-Katz** [auth0-samples/auth0-react-samples#158]
Hey, I followed the "calling-an-api" example and I have one issue , since all my routes are supposed to be secured instead of creating the callApi (from the ExternalApi component) method in each component that needs to fetch data from the server (almost all of them) I wanted to make the callApi a function in the utils that receive a route and then it will fetch the token with "getTokenSilently" and get the data but I cant find a way to do it.

The "getTokenSilently" is a hook function and cannot be called in a nested function (getting this error: "Invalid hook call. Hooks can only be called inside of the body of a function component.")

How can the callApi be used like a global/utils function in every component in my app?

Thanks for the help!

**Comment by stevehobbsdev** [comment]
Hi @Alon-Katz,

You can create a custom hook to do what you want, that wraps your HTTP library and uses the Auth0 hook. Here's a naive implementation. Put this into a new file that you can include in your components that need HTTP access:

```js
import React, { useContext } from "react";
import { useAuth0 } from "../react-auth0-spa";

// Create a new context
const HttpContext = React.createContext();

// Custom hook that uses this context
export const useHttp = () => useContext(HttpContext);

// Provider of the `call` method. This should also
// take any custom options you want to pass to your HTTP workhorse
export const HttpProvider = ({ children }) => {
  // Use the Auth0 hook as normal
  const { getTokenSilently } = useAuth0();

  // Function to call URLs
  const call = async url => {
    // Get the token..
    const token = await getTokenSilently();

    // .. and attach it to the request
    const response = await fetch(url, {
      headers: {
        Authorization: `Bearer ${token}`
      }
    });

    return response.json();
  };

  // Return the provider component, making sure you render the childen
  return (
    <HttpContext.Provider
      value={{
        call
      }}
    >
      {children}
    </HttpContext.Provider>
  );
};
```

This gives you a custom hook that wraps your favourite Http library (I've used `fetch` here) and attaches tokens to it.

To use it, wrap your components in `index.js`:

```js
// index.js

import { HttpProvider } from "./utils/httpProvider";

// ..

ReactDOM.render(
  <Auth0Provider
    domain={config.domain}
    client_id={config.clientId}
    audience={config.audience}
    redirect_uri={window.location.origin}
    onRedirectCallback={onRedirectCallback}
  >
    <HttpProvider>
      <App />
    </HttpProvider>
  </Auth0Provider>,
  document.getElementById("root")
);
```

Then when you want to make an Http call, in your component:

```js
import { useHttp } from './utils/http';  // or whatever your filename is

// ..

const Component = async () => {
   const { call } = useHttp();

   const response = await call('/my/api')
}
```

Hopefully that will get you started!

**Comment by Alon-Katz** [comment]
Thanks so much! Everything now works great!

**Comment by stevehobbsdev** [comment]
@Alon-Katz No problem!
