### ISSUE TITLE
Invalid State error every time

### ISSUE THREAD

**Issue by AntoLepejian** [auth0-samples/auth0-react-samples#161]
Hey ,
![image](https://user-images.githubusercontent.com/35133032/66739147-cbfa8a00-eebb-11e9-8233-e014f888f287.png)

So I am running into this same problem every single time I try to login (my app and even the sample one i downloaded from quickstart). what I found was that I press the login button and it takes me to the universal login page, I then continue with face and when it redirects me to my website, the url is
`http://localhost:3000/?code=QzXu82CDUz4mWykJ&state=STFZb3JPZGZiMVdQSk5aV1drSkVwd2VLSzNYWE0zS09DZEJFTlBmNTlFQQ%3D%3D#_=_ `
and I get the invalid state error with this error in the console
`Uncaught (in promise) Error: Invalid state at t.<anonymous> (auth0-spa-js.production.js:1653) at auth0-spa-js.production.js:141 at Object.next (auth0-spa-js.production.js:153) at auth0-spa-js.production.js:62 at new Promise (<anonymous>) at r (auth0-spa-js.production.js:39) at t.handleRedirectCallback (auth0-spa-js.production.js:1639) at initAuth0 (react-auth0-spa.js:26)`

However, immediately after, if I go to localhost:3000 and click login again I get logged in without going through the universal login page.

I tried clearing cookies, caches, local storage etc.. even incognito and other browsers. The issue happens every time both on localhost and in production mode.

**Comment by stevehobbsdev** [comment]
Hi @AntoLepejian, this looks related to the SDK rather than the sample itself, so I'll close this for now. If you woudn't mind continuing to follow the discussion here: https://github.com/auth0/auth0-spa-js/issues/245
