### ISSUE TITLE
Using in a JS file outside of component

### ISSUE THREAD

**Issue by jnystrom** [auth0-samples/auth0-react-samples#163]
I have an API that I am trying to get access to token to push over to my api, but I cannot reference the needed function

`import { useAuth0 } from "../react-auth0-spa";`

Error:

<img width="984" alt="Screen Shot 2019-10-21 at 6 41 58 PM" src="https://user-images.githubusercontent.com/1293142/67248480-9e20c280-f432-11e9-8d36-a1923cded615.png">

**Comment by jnystrom** [comment]
What is the way I should use to get access to my auth0 token in my API without having to pass it around from components to actions to api?

**Comment by jnystrom** [comment]
@stevehobbsdev any ideas?

**Comment by luisrudge** [comment]
Hooks can only be used from the inside of React Components. If you want to use the SDK from a regular javascript code, you can use our code samples from the docs: https://auth0.com/docs/libraries/auth0-spa-js

Ideally, you want to create a `useAPI` hook that will be able to consume the react wrapper, get the token and run your api call.

Here's an example using `axiso` that I use in my personal apps:

```js
import { useRef, useEffect } from 'react';
import axios from 'axios';

import { useAuth0 } from './react-auth0-spa-js';

export default () => {
  const { getTokenSilently, loginWithRedirect } = useAuth0();
  const api = useRef(
    axios.create({
      baseURL: `${process.env.REACT_APP_API_URL}`
    })
  );
  useEffect(() => {
    const currentAPI = api.current;
    const requestInterceptorId = currentAPI.interceptors.request.use(async config => {
      const token = await getTokenSilently();
      config.headers.authorization = `Bearer ${token}`;
      config.cancelToken = axios.CancelToken.source().token;
      return config;
    });
    const responseInterceptorId = currentAPI.interceptors.response.use(null, async error => {
      if (error.config && error.response && error.response.status === 401) {
        await loginWithRedirect({
          redirect_uri: window.location.origin
        });
      }

      return Promise.reject(error);
    });
    return () => {
      currentAPI.interceptors.request.eject(requestInterceptorId);
      currentAPI.interceptors.response.eject(responseInterceptorId);
    };
  });
  return api.current;
};

```


Then, from my components, I use it like this:

```js
  const api = useApi();
  const [data, setData] = React.useState({});
  
  React.useEffect(() => {
    const load = async () => {
      const { data: products } = await api.get(`/api/users`);
      setData(products);
    };
    load();
  }, []);
```

**Comment by jnystrom** [comment]
I am using Redux, so the API is not contacted via a component, it is called from the redux action.
