### ISSUE TITLE
01-Login example fails

### ISSUE THREAD

**Issue by develeon** [auth0-samples/auth0-react-samples#165]
Tried 01-login, latest master 0f1f7068b186d9f5dc4d4a4e9bebcde1ebfdfc6d 
Basically it hangs on loading (displaying spinner), also tried from docker same thing.
The dashboard logs says "Success exchange", seems broken.

**Comment by stevehobbsdev** [comment]
Hey @develeon, this normally points to a configuration problem. Could you check the FAQ for auth0-spa-js, in particular [this point about initialization time](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-does-the-auth0client-object-take-a-long-time-to-initialize) and see if that fixes your issue?
