### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by edward-of-clt** [auth0-samples/auth0-react-samples#166]
The previous ticket pertaining to this issue was closed - however it's still a very relevant issue. If domains will continue to support `-` so should the examples.

relates to #40 

When attempting to validate the login at https://my-domain.auth0.com/oauth/token this gets returned: 

```json
{"error":"access_denied","error_description":"Unauthorized"}
```

**Comment by joshcanhelp** [comment]
@edward-of-clt - I totally agree. Assigning this to myself to reproduce and either fix or pass along to a maintainer.

**Comment by stevehobbsdev** [comment]
Apologies for the radio silence here. If there is still an issue with the domain here it's more likely to be with Auth0 server than this sample. Please can you raise your issue in the [Auth0 community forums](https://community.auth0.com) if it's still relevant.
