### ISSUE TITLE
web page becomes too slow on reloading in chrome

### ISSUE THREAD

**Issue by Tarun047** [auth0-samples/auth0-react-samples#169]
Steps to reproduce:
 - Download the repo and configure as per your account details.
 - Run project with yarn start
 - Once logged in via Google Oauth, try to reload the page
Expected Behaviour:
  - Web page loads faster and shows the home page
Actual Behaviour:
  -  Web page keeps on showing the loading screen.
All latest packages installed via yarn

**Comment by ceverard9** [comment]
I have the exact issue. Happened to me with the app I was working on. Came here to test their project and am having the same experience in it as well. After logging in if I refresh the page I get the spinner for sometimes 2 minutes before finally seeing the profile page.
