### ISSUE TITLE
04-Authorization examples and direction

### ISSUE THREAD

**Issue by kurtzilla** [auth0-samples/auth0-react-samples#17]
Wondering if there may be a screencast or similar to demonstrate the implementation of 04-Authorization?

The provided code shows how to include the scope for writing messages for all users who login via auth0. But what are some recommended ways to limit grant/allow privileges based on the actual user?

I think there would would be a way to setup a rule that inspects a users login info and assigns scopes per the login (based on email or username), but am afraid that this may eventually prove unwieldy, so is there a method where I could add a scope programmatically to the token after it has been issued? Perhaps by setting up some sort of API call?

**Comment by kurtzilla** [comment]
While I am still on the hunt for more complete documentation and walkthroughs for the management api, it looks like the Authorization Extension may suit my needs.

Do other resources exist for demonstrating the implementation?

**Comment by chenkie** [comment]
there aren't any screencasts that I'm aware of unfortunately.

I'd recommend using rules to restrict which users can receive which scopes. [This doc](https://auth0.com/docs/rules/current) would be a good place to start for that.
