### ISSUE TITLE
04-Authorization errors with Authorization Extension

### ISSUE THREAD

**Issue by kurtzilla** [auth0-samples/auth0-react-samples#18]
Going through the motions of 04-Authorization and receiving the following when trying to log in:

![screen shot 2017-06-29 at 11 47 45 am](https://user-images.githubusercontent.com/579932/27702343-f79be670-5cc0-11e7-9468-e76581011aac.png)

Error: invalid_token. Check the console for further details.

Console:
Object {error: "invalid_token", errorDescription: "Algorithm HS256 is not supported. (Expected algs: [RS256])"}

This came about from changing the app's client type from `Single Page Application` to `Regular Web Application` to accommodate the inclusion of the `Authorization Extension`. 

Is there a workaround to this? I would like to start investigating using the Auth Extension, but can't find where to change the hashing algorithm.

**Comment by chenkie** [comment]
You'll need to keep your client type as single page application to make sure you get the proper flows. For more info on the authorization extension, it's probably best to seek out help with [Auth0 support](https://support.auth0.com).
