### ISSUE TITLE
UnknowN casauth0.js HTTP request giving 404

### ISSUE THREAD

**Issue by ilyas-shah** [auth0-samples/auth0-react-samples#180]
I am having issue while displaying the login page. I am getting a 404 that breaks the login page.
![image](https://user-images.githubusercontent.com/11559665/75249745-daa76500-57fc-11ea-82e7-0155532e360f.png)

**Comment by stevehobbsdev** [comment]
Hi @ilyas-shah 

Have you modified the sample in any way other than using your own Auth0 tenant? Do you have any custom rules or a custom login template set up on your account?

**Comment by ilyas-shah** [comment]
Sorry for this issue. It was happening from the universal login page side.
