### ISSUE TITLE
Redirect after authenticating does not work with routes that contain params

### ISSUE THREAD

**Issue by mogusbi-motech** [auth0-samples/auth0-react-samples#187]
Hi,

The example `PrivateRoute` component does not work with routes that contain params, so something like `<PrivateRoute path="/user/:id" component={User} />` would literally redirect you to `https://example.com/user/:id` after authenticating rather than the using the id on the page you redirect from

Is there any way to get it to read the param value?

**Comment by picosam** [comment]
I second that, I’m facing the exact same issue.

**Comment by stevehobbsdev** [comment]
@adamjmcgrath Could you evaluate this please?

**Comment by adamjmcgrath** [comment]
@mogusbi-motech thanks for reporting

We need to apply the following fix https://github.com/auth0/docs/pull/8829
