### ISSUE TITLE
Error after Sign In then Reload Page

### ISSUE THREAD

**Issue by louischendoit** [auth0-samples/auth0-react-samples#192]
Im using react and using hashroute. Its Problem?

I am following quick start, all setup done(Client Side). Im do login(succes) and redirect to my page. But, when i do the reload page and Uncaught TypeError: Cannot read property ‘loginWithRedirect’ of undefined. even im using ‘logout’ its same error/

**Comment by stevehobbsdev** [comment]
@louischendoit When using the SDK, you must take care to ensure that the SDK has finished loading before you can access its methods. Normally this means doing something like

```js
const auth0 = await createAuth0Client({ ... });

// Now you can call methods
const token = await auth0.getTokenSilently();
```

Does that help?

**Comment by AshishKapoor** [comment]
If you are **only** using social logins you need to check 
```Connections > Social > <Your Social Login Provider>```

Note: Make sure you are are providing the `client ID` and `client secret`.

**Comment by stevehobbsdev** [comment]
@louischendoit Closing for now but feel free to continue the conversation if the above suggestions do not help.
