### ISSUE TITLE
NavBarBrand icon location

### ISSUE THREAD

**Issue by mckenzig** [auth0-samples/auth0-react-samples#193]
Thanks for this project - very cool and easy to get up and running.

React Newbie question:

https://github.com/auth0-samples/auth0-react-samples/blob/master/02-Calling-an-API/src/components/NavBar.js

In your navbar, you have this code:

`<NavbarBrand className="logo" />`

This seems to result in your autho logo being inserted but I do not see that logo packaged in the repo, and I do not see any reference to logo in css files.

How can I change the icon (or at least understand how the URL to the icon is specified)?

Thanks.

**Comment by stevehobbsdev** [comment]
Hi @mckenzig, the logo image is specified as an inline SVG straight into the CSS: https://github.com/auth0-quickstarts/samples-bootstrap-theme/blob/master/src/scss/_icons.scss

You can override and change it by overriding `.logo` and specifying a new background image rule.

Hope that helps!
