### ISSUE TITLE
03-Calling-an-API. Errors with Call Private button. and 04-Authorization browser console Error

### ISSUE THREAD

**Issue by JustFly1984** [auth0-samples/auth0-react-samples#20]
Hello.

I made a free account in auth0. I created a Client. 01 and 02 had no issues, but 03 and 04 does.

Call Private button onClick, I have output: Unauthorized

in terminal I have Error:
```
API Request (port 3001): GET /api/public 200 3.275 ms - 91
API Request (port 3001): GET /api/private 401 6.557 ms - 569
UnauthorizedError: jwt malformed
    at /Users/justfly/projects/auth0-react-samples/03-Calling-an-API/node_modules/express-jwt/lib/index.js:102:22
    at /Users/justfly/projects/auth0-react-samples/03-Calling-an-API/node_modules/jsonwebtoken/verify.js:27:18
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
API Request (port 3001): GET /api/public 304 0.946 ms - -
API Request (port 3001): GET /api/private 401 0.758 ms - 569
```

04 also doesn't want to run with Error in browser console:
```
Uncaught TypeError: Cannot read property 'split' of null
    at Auth.userHasScopes (bundle.js:58757)
    at App.render (bundle.js:37538)
    at bundle.js:27331
    at measureLifeCyclePerf (bundle.js:26611)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (bundle.js:27330)
    at ReactCompositeComponentWrapper._renderValidatedComponent (bundle.js:27357)
    at ReactCompositeComponentWrapper.performInitialMount (bundle.js:26897)
    at ReactCompositeComponentWrapper.mountComponent (bundle.js:26793)
    at Object.mountComponent (bundle.js:14796)
    at ReactCompositeComponentWrapper.performInitialMount (bundle.js:26906)
```

PS Node 8.1.2, npm 5.0.4

**Comment by chenkie** [comment]
It's very likely that you have an opaque `access_token` rather than a JWT `access_token` which happens when you haven't set your `audience` to be an API that you create in the Auth0 dashboard.

Have you followed the [quickstart steps](https://auth0.com/docs/quickstart/spa/react/03-calling-an-api) for calling an API? It describes the steps to follow to obtain a JWT `access_token`.

**Comment by rodrigoap** [comment]
The problem is that you are using the access_token instead of the id_token in authFetch.
In Auth.js create a method to return the id_token, then call it from authFetch.

**Comment by chenkie** [comment]
**Never** use the `id_token` to protect your API. You should only use the `access_token`. Please follow the steps in the [React Calling an API quickstart](https://auth0.com/docs/quickstart/spa/react/03-calling-an-api) as well as the [backend/API quickstart](https://auth0.com/docs/quickstart/backend) which suites your tech stack.

**Comment by rodrigoap** [comment]
Well, the [03-Calling-an-API](https://github.com/auth0-samples/auth0-react-samples/tree/master/03-Calling-an-API) sample doesn't work, it complains that the token is not a JWT. The call from the frontend to the API server has the access_token in the Authotization header that causes the "jwt malformed" error.
How do you get a valid JWT from the access_token in the API server?

**Comment by chenkie** [comment]
Did you follow the steps to set up an API in the Auth0 dashboard and set the `audience` to its identifier? The steps are in the [quickstart](https://github.com/auth0-samples/auth0-react-samples/tree/master/03-Calling-an-API).

**Comment by rodrigoap** [comment]
Yes, audience: 'https://rodrigoap.auth0.com/userinfo'
Is the returned `access_token` supposed to be a JWT token? Because I'm getting a 16 characters string.

**Comment by chenkie** [comment]
When you set it to the `/userinfo` endpoint it will be a 16 character string yes. The `audience` needs to be set to the identifier for your API that you create in the [APIs section](https://manage.auth0.com/#/apis) of the Auth0 dashboard. Read the "checkpoint" notes [here](https://auth0.com/docs/quickstart/spa/react/03-calling-an-api#set-the-audience-and-scope-in-auth0-webauth) for more.

**Comment by rodrigoap** [comment]
oh lord! When creating the API I set Identifier as `https://rodrigoap.auth0.com/userinfo`, I changed it to somethig else and it worked. I guess that `https://rodrigoap.auth0.com/userinfo` must not be a valid identifier because it's kind of a reserved id in auth0.
Thanks for your help!

**Comment by chenkie** [comment]
No problem. Perhaps this is something we should note in the quickstarts for clarity. I'll add it 👍
