### ISSUE TITLE
Erroneous config  in auth0-react-samples/Sample-01/src/auth_config.json.example

### ISSUE THREAD

**Issue by whatisthejava** [auth0-samples/auth0-react-samples#201]
Hi

I signed up to auth0 and followed the sample app walkthru for configuring my react app to use auth0

I configured my client and then followed this. 

https://auth0.com/docs/quickstart/spa/react

I downloaded the sample app and attempted to run it.

On redirect to the IDP I receive this error message

Oops... Service not found: YOUR_API_IDENTIFIER

The walkthru doesnt mention this and doesnt hint at what I should do. 

A bit of trial and error and i deleted the line from config 

from this 

```
{
  "domain": "MY_DOMAIN",
  "clientId": "MY_CLIENT_ID",
  "audience": "{API_IDENTIFIER}"
}
```
to this 

````
{
  "domain": "MY_DOMAIN",
  "clientId": "MY_CLIENT_ID"
}
```

And I successfully logged in.

(I know i will need an audiance later but just not now )

Thanks

**Comment by stevehobbsdev** [comment]
Hi @whatisthejava, thanks for raising this. Yes for the full sample to work you will need to go through and create the API artifacts in the dashboard.

Let me update the readme with this info.
