### ISSUE TITLE
In Dockerfile base image name "build" is meaningless

### ISSUE THREAD

**Issue by marcinnowakowski** [auth0-samples/auth0-react-samples#203]
I have a suggestion to use more meaningful name for base docker image in Dockerfile:
https://github.com/auth0-samples/auth0-react-samples/blob/master/Sample-01/Dockerfile

IS:
`FROM node:10-alpine AS build`,
MIGHT BE:
`FROM node:10-alpine AS node-alpine-base-image`.

**Comment by stevehobbsdev** [comment]
Thanks for the report. It felt meaningful at the time as the base image is designed as a "build" stage that compiles the artifacts for the next stage, which is to run the app.

This isn't unusual practise and something that is used in the [docker docs themselves](https://docs.docker.com/develop/develop-images/multistage-build/#name-your-build-stages).
