### ISSUE TITLE
Refreshing the page - need to relogin?

### ISSUE THREAD

**Issue by maximus321** [auth0-samples/auth0-react-samples#204]
I am following the tutorial, but when I refresh the page, I have to login again, is that normal behavior?
Thanks!

EDIT: I am using code grant flow with PKCE, 
I disabled Implicit flow on auth0, as this is deprecated, not sure why still allowed for new app? food for toughts

`{
  "date": "2020-07-10T18:58:18.275Z",
  "type": "fsa",
  "description": "Login required",
  "client_id": "JcrmIx7PTU4dBSVGm19fswxL5HEHeQb2",
  "client_name": "react-js-max",
  "ip": "192.222.159.206",
  "user_agent": "Chrome 83.0.4103 / Windows 10.0.0",
  "details": {
    "body": {},
    "qs": {
      "audience": "sample",
      "client_id": "JcrmIx7PTU4dBSVGm19fswxL5HEHeQb2",
      "redirect_uri": "http://localhost:3000",
      "scope": "openid profile email",
      "response_type": "code",
      "response_mode": "web_message",
      "state": "MDlndFFJY2xTTHZtLkFSOF9Rdi44cFloVGRrYVVleFB0djQ5WEgxQkFZYQ==",
      "nonce": "RH5OT2d3ckJFcUJCN1lLflByUjh+M3FVaUNoRW9jNEdtVDZsRHdiWUZMWQ==",
      "code_challenge": "etNPe54AO-ZOcLLvL6vGYUnLoszzvAhPYfZVQGORegY",
      "code_challenge_method": "S256",
      "prompt": "none",
      "auth0Client": "eyJuYW1lIjoiYXV0aDAtcmVhY3QiLCJ2ZXJzaW9uIjoiMS4wLjAifQ=="
    },
    "connection": null,
    "error": {
      "message": "Login required",
      "oauthError": "login_required",
      "type": "oauth-authorization"
    }
  },
  "hostname": "dev-maximus.us.auth0.com",
  "audience": "sample",
  "scope": [
    "openid",
    "profile",
    "email"
  ],
  "auth0_client": {
    "name": "auth0-react",
    "version": "1.0.0"
  },
  "log_id": "90020200710185823136000839541731034680291360638681219074",
  "_id": "90020200710185823136000839541731034680291360638681219074",
  "isMobile": false
}`

**Comment by xavicolomer** [comment]
@maximus321 I am also having the same problem. Did you find a solution?

**Comment by stevehobbsdev** [comment]
@maximus321 Are you signing in using a social connection such as Google? If so, check that you are not using Auth0's development keys for the Google connection in your Auth0 Dashboard. There is a limitation where you cannot silently reauthenticate unless you specify your own keys.

Also verify that you are not using a browser extension that blocks third-party cookies, as this will also cause logging in on refresh to fail.

**Comment by maximus321** [comment]
Yes I was using Google SSO and my personnal account.
I will double check this when I got some time and edit here with my findings
Thanks!

**Comment by stevehobbsdev** [comment]
Great! Thanks @maximus321.

**Comment by stevehobbsdev** [comment]
@xavicolomer If you continue to have issues, please raise a new issue with the details of your scenario.
