### ISSUE TITLE
02 - Custom Login Form Handle Authentication

### ISSUE THREAD

**Issue by jasonalvis** [auth0-samples/auth0-react-samples#21]
Hello,

I've been trying out the demo under the `embedded-login` branch but it doesn't appear to authenticate the user when logging in with Google for example. 

After debugging I noticed `handleAuthentication` doesn't get called when logging in - its not part of the constructor in `Auth.js`. 

In comparison to the 01 - Embedded-Login example it is [present in the constructor](https://github.com/auth0-samples/auth0-react-samples/blob/embedded-login/01-Embedded-Login/src/Auth/Auth.js#L21).

When I add it in it works as expected. Could we [add it in](https://github.com/auth0-samples/auth0-react-samples/blob/embedded-login/02-Custom-Login-Form/src/Auth/Auth.js#L14) as part of the repo?

`
this.handleAuthentication();
`

Unless I'm miss-understanding something and there is another issue here?

**Comment by chenkie** [comment]
In the custom login form sample, the authentication handling actually happens in `routes.js`. https://github.com/auth0-samples/auth0-react-samples/blob/embedded-login/02-Custom-Login-Form/src/routes.js#L12-L16

There we are checking whether `access_token`, `id_token`, or `error` are present in the authentication hash that comes back from Auth0. If so, we call `handleAuthentication`.

Are you getting any errors when you log in with Google and you don't have `this.handleAuthentication` being called in your `Auth` service constructor?

**Comment by jasonalvis** [comment]
Hey @chenkie,

My mistake - my callback URL was wrong.

I had it set as `http://localhost:3000` rather than `http://localhost:3000/callback`

Its all working now as expected, lots to learn still with react! 😀

Thanks for replying
