### ISSUE TITLE
useAuth0().isAuthenticated returns initialy false then true

### ISSUE THREAD

**Issue by maces-13** [auth0-samples/auth0-react-samples#210]
when accessing 
```
useAuth0().isAuthenticated
```
the return will always be false until the Auth0 finishes loading, this is already raised as a topic with my personal work around on Auth0 community;
https://community.auth0.com/t/useauth0-isauthenticated-returns-initialy-false-then-true/47434/3

**Comment by d-javed** [comment]
Hello - I have too been experiencing this issue - there is a workaround using isLoading but that is only limited on specific use cases. Some components flicker as I show them based on isAuthenticated. The flag returns as false on the first call then returns true.

**Comment by frederikprijck** [comment]
When using an SPA, there is always an initial period of time where you are unable to know if the user is logged in or not.
Even when using LocalStorage and having a token in the local storage, our SDK still has to make a request to Auth0 to verify if the user is still logged in with Auth0.

This is why we have the `isLoading` property. You should rely on isLoading before calling isAuthenticated.
