### ISSUE TITLE
way too many deprecated libraries

### ISSUE THREAD

**Issue by Jay-study-nildana** [auth0-samples/auth0-react-samples#212]
Folks,

I like the Auth0 samples in general but this one, in particular, has way too many deprecated libraries. some of the libraries are not even maintained anymore. 

any chance you might be upgrading this sample soon?

**Comment by stevehobbsdev** [comment]
👋  We have just updated the sample. It would help if you could identify which libraries in particular that are causing an issue.

**Comment by Jay-study-nildana** [comment]
hey @stevehobbsdev 

I downloaded a fresh sample yesterday. let me run that again and put the error messages here. 

Here you go. 

> npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
> 
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> 
> npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
> 
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> 
> npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
> 
> npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
> 
> npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
> 

I got no complaints, because, it works beautifully. and, the steps are very clear on how i can use it in my own react app (in which case, of course, these errors wont exist because i will be create everything new)

but, sometimes, I want to demo Auth0 to my potential clients, they see this and they get scared.  Like, when I trying to upsell Auth0 and they want to see some direct samples and all that.

**Comment by stevehobbsdev** [comment]
I'll keep this open and try to update the libraries 👍

**Comment by Jay-study-nildana** [comment]
@stevehobbsdev 

sounds good. its not a hurry situation. the app works just fine except for so many warnings :)

**Comment by Jay-study-nildana** [comment]
Today, I just realized that its fairly straightforward to update to the latest packages and get rid of most of the errors. 

Some errors remain but they have nothing to do with the sample itself. 

```
    $ npx npm-check-updates -u
    $ npm install 
```

I even added typescript to the Auth0sample, and nothing has broken so far. 

@stevehobbsdev you can close this issue. I have solved it and put the notes here in this comment. but if you want to keep it open and do the updates and then close, that is always better, yes. meanwhile, other developers who come here can simply update and solve it on their own.

**Comment by stevehobbsdev** [comment]
Keeping this open, will hopefully be resolved by #224

**Comment by frederikprijck** [comment]
Closing because https://github.com/auth0-samples/auth0-react-samples/pull/224 got merged
