### ISSUE TITLE
doesnt work out of the box?

### ISSUE THREAD

**Issue by sw-yx** [auth0-samples/auth0-react-samples#216]
hello! thanks for this sample.

<details>
<summary>
I set it up on my machine with a test auth0 app:
</summary>

![image](https://user-images.githubusercontent.com/6764957/103934848-ab71bc00-5160-11eb-8412-899d64057b35.png)

</details>

<details>
<summary>
with no other modifications. it just times out with a really opaque error:
</summary>

![image](https://user-images.githubusercontent.com/6764957/103934901-bf1d2280-5160-11eb-9fcc-02ff5038850e.png)

</details>

i'd love to know if this sample needs additional setup than that, or if i have somehow misconfigured?

**Comment by frederikprijck** [comment]
Hi @sw-yx,

Sorry for the inconvenience!

It seems to work fine for me when I try a clean `master` checkout.
I see your console is showing an error, would u be able to share the error?

I am also trying to understand two things:

- Why is the call to localhost showing an XHR type
- What is content.css?

This is my network tab when I open the application, its showing type Document for the localhost call and it doesn't have any call to content.css:

![image](https://user-images.githubusercontent.com/2146903/103945767-f6c2a500-5135-11eb-8bb0-1bad5fa52ae4.png)

Is there anything useful in your tenant logs?

**Comment by sw-yx** [comment]
hey Frederik you know what this is embarrassing... i literally tried doing the exact same thing *and it worked*. ugh. heisenbug. sorry for the trouble and i will come back only if i can really find a repeatable problem.

as for the `content.css` - that's a chrome extension i have. sorry i should have sent a screenshot using incognito so it wouldnt insert random noise.

thank you and sorry again!

**Comment by sw-yx** [comment]
actually.. the moment i refresh... this happens

![image](https://user-images.githubusercontent.com/6764957/103948547-e41b9080-5174-11eb-88be-5646c412b8c8.png)


my console error says `Failed to load resource: the server responded with a status of 400 ()`

**Comment by sw-yx** [comment]
ah. when i inspect the html of the error, i see this hidden important detail.

```html
    <div class="error-footer">
        <div class="footer-groups cf">
          <span class="footer-group">
            <i class="footer-group-icon read-docs"></i>
            <h4 class="footer-group-title">TECHNICAL DETAILS</h4>
            <a href="#" class="toggle-details">See details for this error</a>
          </span>
          <span class="footer-group">
            <h4 class="footer-group-title">SUPPORT</h4>
            
              <p class="footer-group-detail">Please contact the systems administrator.</p>
            
          </span>
        </div>
        <div class="error-details">
          <p class="error-status">
            
            <strong>invalid_request</strong>: The specified redirect_uri &#39;http://localhost:3000&#39; does not have a registered origin.
            
          </p>
          
          <a href="https://manage.auth0.com/#/logs/" target="_new" class="view-logs-btn">VIEW LOG</a>
          

          
          <span class="error-id">
            <span class="error-id-title">TRACKING ID: </span><span class="error-id-content">7db8c8e6600f2cdd9829</span>
          </span>
          
        </div>
```

i recommend not hiding it...

**Comment by frederikprijck** [comment]
The error is happening in the iframe that we are using.
The same error should show up in your Auth0 Tenant logs.

To fix this, add `http://localhost:3000` in your applications Settings in Auth0 as an **Allowed Web Origin**.

**Comment by sw-yx** [comment]
ok it looks like i didnt add logout url and web origins. once i added it, i could login just fine.

![image](https://user-images.githubusercontent.com/6764957/103949173-d31f4f00-5175-11eb-8764-9ccf27e4a4ae.png)

so the misconfiguration was my fault, but ultimately this may be a common failure mode for people trying this out - you may wish to have a better error message experience here! closing for now and leaving that up to you.

**Comment by frederikprijck** [comment]
@sw-yx The sample is intended to be used while following our React Quickstart at https://auth0.com/docs/quickstart/spa/react/01-login, there it mentions to configure those things before continuing.

Happy you solved it!
