### ISSUE TITLE
01-Embedded-Login: Invalid Token after login

### ISSUE THREAD

**Issue by danieloliveira079** [auth0-samples/auth0-react-samples#22]
After clicking login and authorise the app to access my details the following error shows up in the browser concole.

Object {error: "invalid_token", errorDescription: "Algorithm HS256 is not supported. (Expected algs: [RS256])"}

Browser: Chrome
Connection: Google
NodeJS: 8

**Comment by danieloliveira079** [comment]
Just found https://github.com/auth0/auth0.js/issues/303

I would encourage to that be the default value for the Default App.

**Comment by chenkie** [comment]
Hi @danieloliveira079 

Glad you found the solution. The default has recently been changed for new Auth0 tenants. If you created your account some time ago, that may be why the new default isn't reflected for you.
