### ISSUE TITLE
just a spinning circle

### ISSUE THREAD

**Issue by logemann** [auth0-samples/auth0-react-samples#228]
all i get is a spinning circle without any error in console.

**Comment by logemann** [comment]
.. and a "oops timeout".

**Comment by logemann** [comment]
Solved it by putting in a WebOrigin in the Auth0 management console. Should be documented.

**Comment by frederikprijck** [comment]
@logemann Sorry for the confusion here. Worth pointing out that, as mentioned in the readme, the sample is intended to be used while following our [quickstart](https://auth0.com/docs/quickstart/spa/react), which has the following section:

![image](https://user-images.githubusercontent.com/2146903/119002022-cb29b400-b98c-11eb-830d-a5c594a6be3b.png)
