### ISSUE TITLE
failed to load resource the server responded with a status of 400 () in React Node

### ISSUE THREAD

**Issue by nikitaghule98** [auth0-samples/auth0-react-samples#234]
this is register page of my project
![image](https://user-images.githubusercontent.com/84223668/131256256-bb76833e-3c67-4025-9574-d3fa4233e61a.png)
when i enter email address it send link as i've used firebase for authentication
![image](https://user-images.githubusercontent.com/84223668/131256275-968146d0-5a0d-4497-af2b-d127799b7cca.png)
it redirects me to the page where i want to add password for registration
after completing registration it redirects me to home page but it doesn't shows any logged in user and the error is like this
![image](https://user-images.githubusercontent.com/84223668/131256388-92f0654b-37a0-49c8-b073-257ecdf50e24.png)
![image](https://user-images.githubusercontent.com/84223668/131256408-6aea228c-d72a-48f8-a696-c0e964664b36.png)
![image](https://user-images.githubusercontent.com/84223668/131256420-bca609d2-ac8f-4310-a410-10e412c6bf3c.png)
![image](https://user-images.githubusercontent.com/84223668/131256430-774a436a-2ff8-4fec-b7eb-bd759904a514.png)

code files are available on my github account :  
https://github.com/nikitaghule98/Ecommerce-website-using-react-Backend.git
https://github.com/nikitaghule98/Ecommerce-website-using-react-Frontend.git

**Comment by stevehobbsdev** [comment]
Hi @nikitaghule98, these samples are specifically for our Auth0 React SDK - there's nothing in the debug images nor the code you've supplied which suggests you're using our products, so unfortunately we cannot help you.

If it's a Firebase problem, I would suggest you try to get some help on their GitHub or in their community support portals.

Sorry I couldn't be of more help!
