### ISSUE TITLE
forceRefresh - Why?

### ISSUE THREAD

**Issue by Siyfion** [auth0-samples/auth0-react-samples#24]
In all the examples, you set the `createHistory` options to the following:
``` js
export default createHistory({
  forceRefresh: true
})
```

This causes a full page refresh after every route change, if I have understood the documentation for `history` correctly. So why is this the "sample" way?

**Comment by chenkie** [comment]
We get some strange behavior with the Callback route when it's set to `false` where app will route back to `/home` upon auth completion but the Callback route hangs in the view. There might be a better way to solve it with the router though so I'm open to suggestions. That being said, navigation between different routes doesn't actually cause a full page refresh in this setup, only on logout does it do so.

**Comment by Siyfion** [comment]
@chenkie Agreed, there is some weird behaviour with `Callback` after removing it. Though I don't fully understand why it only causes a forced refresh when logging out? Don't get me wrong, I've tested, and I can see that it does, but I thought it would have caused a full refresh on *any* route change... why is this?

**Comment by chiss2906** [comment]
I also had some weird behaviour when trying to redirect with history. This solved my problem: https://github.com/auth0-samples/auth0-react-samples/issues/29

**Comment by Siyfion** [comment]
Ah good spot @chiss2906! Perhaps we could get a PR to fix this in the example?

**Comment by chiss2906** [comment]
Here you go: https://github.com/auth0-samples/auth0-react-samples/pull/30

**Comment by chenkie** [comment]
Fixed in latest
