### ISSUE TITLE
Cypress and auth0-react integration not working

### ISSUE THREAD

**Issue by dchoigt** [auth0-samples/auth0-react-samples#247]
I am using the Auth0Provider JSX syntax component. This component causes a redirect to the login screen if a user lands on a page that requires login first. I am trying to integrate my pages, which are cookies based, into Cypress, but I am finding that even after a successful login and setting of the auth0.is.authenticated cookie the screen will still redirect. Which in Cypress is not allowed due to cross domain. What cookies must I set and what are the names and content that is required to stop the redirect and get auth0-react to see that Cypress is logged in? Thank you.

```
Cypress.Commands.add("loginToAuth0", () => {
	cy.loginWithAuth0Client()
		.then(response => {
			console.log("response", response);
			const { 
				accessToken,
				expiresIn,
				idToken,
				scope,
				tokenType 
			} = response;

			cy.getUserInfo(accessToken)
				.then(user => {
					const session = {
						user,
						idToken,
						accessToken,
						accessTokenScope: scope,
						accessTokenExpiresAt: Date.now() + expiresIn,
						createdAt: Date.now()
					}
					const [header, payload, signature] = idToken.split('.');
					const tokenData = jwt.decode(idToken);
					console.log("login auth0 session", session);
					console.log("cookie expires", Math.floor(Date.now() / 1000) + expiresIn)
					cy.setCookie('auth0.is.authenticated', JSON.stringify(true), { expiry: Math.floor(Date.now() / 1000) + expiresIn});
					cy.setCookie('_legacy_auth0.is.authenticated', 'true')
					
					cy.setCookie(
						`@@auth0spajs@@::${Cypress.env("auth_client_id")}::${Cypress.env("auth_audience")}::${scope}`, 
						JSON.stringify({
							body: {
								access_token: accessToken,
								id_token: idToken,
								scope,
								expires_in: expiresIn,
								token_type: tokenType,
								audience: Cypress.env("auth_audience"),
								decodedToken: {
									user: tokenData
								},
								client_id: Cypress.env("auth_client_id")
							},
							expiresIn: Math.floor(Date.now() / 1000) + expiresIn
						}));
				})
		})
})
```

```
Cypress.Commands.add('loginWithAuth0Client', (overrides = {}) => {
	const scope = "openid profile email";
	
	return new Cypress.Promise((resolve, reject) => {
		auth.client.login({
			grant_type: "http://auth0.com/oauth/grant-type/password-realm",
			realm: "Username-Password-Authentication",
			username: Cypress.env("auth_username"),
			password: Cypress.env("auth_password"),
			audience: Cypress.env("auth_audience"),
			scope,
			client_secret: Cypress.env("auth_client_secret")
		}, (loginErr, response) => {
			if (loginErr) {
				console.log("Login to auth0 failed!", loginErr);
				reject(loginErr);				
			} 
			console.log("loginWithAuth0Client has succeeded", response);
			resolve(response);			
		});
	});	
})
```

**Comment by frederikprijck** [comment]
Hey, our SDK itself is tested using Cypress, you should be able to get some inspiration here: https://github.com/auth0/auth0-react/tree/master/cypress.

I know we are still using a redirect, which isn't recommended by Cypress. However, using password grant isn't recommended from a security perspective, and neither is relying on internals of our SDK (the structure of the cookies).

**Comment by dchoigt** [comment]
Thank you for your response. I really appreciate it. I run Cypress 3.x and it does not allow the redirection to the separate login screen, as it considers it a cross domain action. Our app redirects users to a distinct domain to do SSO.

So unfortunately I cannot just type in username and password. So I don't know that I have a choice other than the cookie route. But auth0.is.authenticated is basically ignored and the redirection is still happening. Any other cookies I need to be aware of. Or perhaps using localstorage instead.

Thank you again for your help.
