### ISSUE TITLE
Oops... Unauthorized

### ISSUE THREAD

**Issue by garthtee** [auth0-samples/auth0-react-samples#248]
I get the error `Oops... Unauthorized`. Only changes I've added to the sample is creating the `auth_config.json` and adding my domain and client id properties.

On the Auth0 application config, I've added `http://localhost:3000` to 

- Allowed Callback URLs
- Allowed Callback URLs
- Allowed Web Origins

**Comment by jorgecolon413** [comment]
I getting the same error with the same configuration. Did you manage to see what was the problem ?

**Comment by jorgecolon413** [comment]
Created another app in the dashboard and used those creds for my app and it worked. Was originally using the Default App that is creates when testing the tool initially.

**Comment by frederikprijck** [comment]
@jorgecolon413 , I assume what got you is what's called out here: https://auth0.com/docs/quickstart/spa/react/01-login

<img width="898" alt="image" src="https://github.com/auth0-samples/auth0-react-samples/assets/2146903/13cce8cb-28d5-4187-a17b-d92495785294">

**Comment by jorgecolon413** [comment]
I looked for that option on the dashboard but it was set to SPA already and I did not manage to find the Token Endpoint Authentication Method option. That's why I finally created the new app through the dashboard.
