### ISSUE TITLE
Do I need to call getAccessTokenSilently every time I make an external API call?

### ISSUE THREAD

**Issue by jlei523** [auth0-samples/auth0-react-samples#255]
In my application, I need to make many calls to an external API. I could not find anything in the docs that tells me how often I should call `getAccessTokenSilently`.

In the examples, I see that `getAccessTokenSilently` is called right before an external API call. But what happens if I have to make external API calls, sometimes back to back to back?

**Comment by stevehobbsdev** [comment]
@jlei523 if you're concerned about the performance of making multiple calls to `getAccessTokenSilently`, by default the SDK will cache the access token for as long as the token is valid (i.e. has not expired), and will not itself make multiple calls to get new access tokens when it doesn't need to.

Does this help?

**Comment by jlei523** [comment]
I think it does. Thanks.
