### ISSUE TITLE
Where is the logic to check if a user already exists or not?

### ISSUE THREAD

**Issue by fresh5447** [auth0-samples/auth0-react-samples#26]
I need to hook into the authentication process but I am not sure where. Basically, the lock will not let you signup an account that already exists. Where is this happening in the code?

I need to also create a new user in the database whenever auth creates a new user, and then simply proceed with the authentication process as normal if it is not a new user.

Is there a hook in the process that allows the Auth process to create a new auth account, or simply log someone in?

None of the info I am logging in the `handleAuthentication` function seems to be relevant:

```
  handleAuthentication() {
    this.auth0.parseHash((err, authResult) => {
      console.log(err)
      console.log(authResult)
      if (authResult && authResult.accessToken && authResult.idToken) {
        this.setSession(authResult);
        history.replace('/home');
      } else if (err) {
        history.replace('/home');
        console.log(err);
        alert(`Error: ${err.error}. Check the console for further details.`);
      }
    });
  }
```

**Comment by chenkie** [comment]
The logic for checking if a user exists all happens in Auth0's backend. The `handleAuthentication` method in these samples is simply to work with the result of an authentication transaction, which in this case is to parse the authentication result hash into a useable object to get the `access_token`, `id_token`, etc.

You'll want to use Auth0's [rules engine](https://auth0.com/docs/rules/current) or [hooks](https://auth0.com/docs/hooks) to augment the authentication pipeline. It's there that you can provide some custom logic to be run based on your needs.

**Comment by fresh5447** [comment]
Thanks, @chenkie that explains why I wasn't able to find it. Rules & Hooks for the win.
