### ISSUE TITLE
How to test the auth actions?

### ISSUE THREAD

**Issue by juliankmazo** [auth0-samples/auth0-react-samples#28]
Would be awesome to have some examples of how to test a login, a signup,  a password recovery.

**Comment by chenkie** [comment]
Thanks for the suggestion. I'll add it to the backlog 👌

**Comment by juliankmazo** [comment]
Thank you for the quick response and these great examples :D

**Comment by luisrudge** [comment]
We recommend using [jest](https://facebook.github.io/jest/). You just mock everything and assert what you expect. We're not adding tests because this is a starting point for your project, which will most likely change and break all the tests anyway.
