### ISSUE TITLE
Adjust your current browser settings from 'Strict' to 'Moderate'.

### ISSUE THREAD

**Issue by kunalsCodiste** [auth0-samples/auth0-react-samples#291]
Unable to detect device share. This may be due to browser security settings. Adjust your current browser settings from 'Strict' to 'Moderate'. Alternatively, login via a Chrome Browser.

**Comment by frederikprijck** [comment]
Thanks for opening this issue.

Can you please elaborate on what you are expecting from us? It's unclear what's happening or what you want us to do with any of the information here.
