### ISSUE TITLE
somebody's credentials

### ISSUE THREAD

**Issue by Amialc** [auth0-samples/auth0-react-samples#3]
(AUTH-3835)
Every sample contains somebody's credentials. For example, [01-basic-login](https://github.com/auth0-samples/auth0-react-samples/blob/master/01-Basic-Login/src/Auth/auth0-variables.js), [02-custom-login-form](https://github.com/auth0-samples/auth0-react-samples/blob/master/02-Custom-Login-Form/src/Auth/auth0-variables.js).

**Comment by chenkie** [comment]
Thanks, they're removed now.
