### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by hurjun1995** [auth0-samples/auth0-react-samples#31]
Hi, I get Access denied; errorDescription: "Cannot read property 'split' of undefined" when I click on facebook login on the lock. Any idea for this error?

**Comment by chenkie** [comment]
It sounds like you are getting an opaque access token rather than a JWT access token. Which step of the samples are you working from?

**Comment by hurjun1995** [comment]
I'm working on the first sample, login. It seems like the error is generated in the function handleAuthentication().

**Comment by chenkie** [comment]
Hmm there isn't any kind of JWT decoding happening at that point. Have you included anything else beyond the sample code to try to decode the token?

**Comment by hurjun1995** [comment]
No, I did not modify the sample code at all. I just did npm install and npm start..

**Comment by chenkie** [comment]
Have you configured Facebook to use your own application keys that you get when registering an app with Facebook?

**Comment by hurjun1995** [comment]
Hmm I don't get what you're saying. I couldn't find anything about configuring  facebook on the quick start.

**Comment by chenkie** [comment]
When you go to enable Facebook logins in the connections page there is an area to fill out your app ID, secret etc. Click into the Facebook connection on [this page](https://manage.auth0.com/#/connections/social) to configure it.

**Comment by hurjun1995** [comment]
![image](https://user-images.githubusercontent.com/30101613/29048515-e421c036-7b85-11e7-8d8c-7f643fd6fce2.png)

I configured the facebook connection and clicked on try on that page(connection), and got this again..

**Comment by chenkie** [comment]
looks like it's an issue on the server side then. I'd recommend opening a ticket with [support](https://support.auth0.com) as it will require some investigation in your account.
