### ISSUE TITLE
Redirecting to page that user logged in from

### ISSUE THREAD

**Issue by ara-vardanyan** [auth0-samples/auth0-react-samples#325]
Hello. I was wondering if there are any example implementations of redirecting users to the url that they signed in from? I am having trouble implementing this feature with auth0. Thanks!

**Comment by frederikprijck** [comment]
Hello,

You should be able to set appState.target when calling loginWithRedirect or using withAuthenticationRequired, that's is what's used to redirect back to a specific route after handeling the callback.

Let me know if that doesnt help.

**Comment by ara-vardanyan** [comment]
Thanks for the quick response! Still encountering the issue of being redirected to the home url. I have made sure to add all necessary callback urls in the application settings.

`
// client/src/main.jsx
import { Auth0Provider } from '@auth0/auth0-react';
import { auth0_domain, auth0_client_id, auth0_audience } from '../config';

ReactDOM.createRoot(document.getElementById('root')).render(
  <BrowserRouter>
    <Auth0Provider
      domain={auth0_domain}
      clientId={auth0_client_id}
      authorizationParams={{
        redirect_uri: window.location.origin,
      }}
      // audience={auth0_audience}
    >
        <App />
    </Auth0Provider>
  </BrowserRouter>
);
`

`
// client/src/components/LoginButton.jsx
import React, { useContext } from 'react';
import { useAuth0 } from '@auth0/auth0-react';
import { AppContext } from '../contexts/AppContext';

const LoginButton = () => {
  const { loginWithRedirect } = useAuth0();
  const { isAuthenticated } = useContext(AppContext);
  const targetPath = window.location.href;

  const handleClick = () => {
    console.log(window.location.href);
    setTimeout(() => {
      loginWithRedirect({ appState: { returnTo: window.location.targetPath } });
    }, 2000); // delay the redirect by 2 seconds so we can log the path (2000 milliseconds)
  };

  return (
    !isAuthenticated && (
      <button onClick={handleClick}>
        Log In
      </button>
    )
  );
};

export default LoginButton;
`

Does the redirectUri specified in the Auth0Provider take precedence over uri specified in the appState.returnTo in the loginWithRedirect function? Really appreciate your help with this issue!

**Comment by ara-vardanyan** [comment]
> Hello,
> 
> You should be able to set appState.target when calling loginWithRedirect or using withAuthenticationRequired, that is what's used to redirect back to a specific route after handeling the callback.
> 
> Let me know if that doesnt help.

Thanks for the quick response! Still encountering the issue of being redirected to the home url. I have made sure to add all necessary callback urls in the application settings.

```
// client/src/main.jsx
import { Auth0Provider } from '@auth0/auth0-react';
import { auth0_domain, auth0_client_id, auth0_audience } from '../config';

ReactDOM.createRoot(document.getElementById('root')).render(
  <BrowserRouter>
    <Auth0Provider
      domain={auth0_domain}
      clientId={auth0_client_id}
      authorizationParams={{
        redirect_uri: window.location.origin,
      }}
      // audience={auth0_audience}
    >
        <App />
    </Auth0Provider>
  </BrowserRouter>
);
```


```
// client/src/components/LoginButton.jsx
import React, { useContext } from 'react';
import { useAuth0 } from '@auth0/auth0-react';
import { AppContext } from '../contexts/AppContext';

const LoginButton = () => {
  const { loginWithRedirect } = useAuth0();
  const { isAuthenticated } = useContext(AppContext);
  const targetPath = window.location.href;

  const handleClick = () => {
    console.log(window.location.href);
    setTimeout(() => {
      loginWithRedirect({ appState: { returnTo: window.location.targetPath } });
    }, 2000); // delay the redirect by 2 seconds so we can log the path (2000 milliseconds)
  };

  return (
    !isAuthenticated && (
      <button onClick={handleClick}>
        Log In
      </button>
    )
  );
};

export default LoginButton;
```

Does the redirectUri specified in the Auth0Provider take precedence over uri specified in the appState.returnTo in the loginWithRedirect function? Really appreciate your help with this issue!

**Comment by frederikprijck** [comment]
You need appState.target, not appState.returnTo.

Would that work ?

**Comment by ara-vardanyan** [comment]
> You need appState.target, not appState.returnTo.
> 
> Would that work ?

That didn't work. What did work however was changing the redirect_uri in the Auth0Provider to window.location.href. Thanks for your help!
