### ISSUE TITLE
isAuthenticated is null in auth0-react

### ISSUE THREAD

**Issue by pandabrand** [auth0-samples/auth0-react-samples#345]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0-samples/auth0-react-samples/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am trying to exclusively use google as a login. I have created credentials in Google for this app. It seems to successfully login but isAuthenticated is always null. I don’t see any type of return in the network tab in devtools(Chrome&Firefox). What am I doing wrong?

### Reproduction

I'll just post the code I'm using:
```
export default function App() {
  return (
    <Auth0Provider
      domain='*******.us.auth0.com'
      clientId='*******'
      authorizationParams={{
        redirect_uri: `${window.location.origin}/admin/dashboard`
      }}
    >
      <BrowserRouter>
        <Routes>
          <Route element={<Layout/>}>
            <Route path='/' index={true} element={<UploadForm/>} />
            <Route path='/login' element={<Login/>} />
            <Route path='/admin' element={<ProtectedRoute/>}>
              <Route path='/admin/dashboard' element={<AdminDashboard/>} />
            </Route>
          </Route>
        </Routes>
      </BrowserRouter>
    </Auth0Provider>
  );
}
```
this is the route component I'm using to check for authentication
```
const ProtectedRoute = () => {
    const { isAuthenticated } = useAuth0()
    return isAuthenticated ? <Outlet /> : <Navigate to='/login' />
}
```

### Which browsers have you tested in?

Chrome, Firefox

**Comment by frederikprijck** [comment]
You can not redirect back to a protected route. You should ensure `redirect_uri` is configured to redirect back to a route that does not require the user to be authenticated.

You can use appState.target to eventualy have the user end up at admin/dashboard.

What you want to achieve is:

- Login is triggered, user is redirect to Auth0
- User logs in
- User is redirected back to the confgured redirect_uri (note: the user is not authenticated in the app yet)
- Our SDK kicks in on that route automatically and ensures to request the neccesary tokens. This is async, but this should eventualy lead to isAuthenticated to be true.
- You can configure `appState.returnTo` and our SDK will redirect to that URL at the end of the process mentioned above.

Let me know if that doesn't help.

**Comment by pandabrand** [comment]
So I've changed my code to closer represent the Sample-01. Which seems to work, however, now when I try to login now I get this error: 'TypeError: Cannot convert a Symbol value to a string' from clicking the login button. 
Coming from auth0-spa-js.production.esm.js
 My code:
```
import React from "react";
import { useAuth0 } from "@auth0/auth0-react";

const Login = () => {
    const { loginWithRedirect, logout, isAuthenticated } = useAuth0()
    const logoutWithRedirect = () =>
        logout({
            logoutParams: {
            returnTo: window.location.origin,
            }
        });

    return (
        <>
            {!isAuthenticated && <button onClick={() => loginWithRedirect()}>Login</button>}
            {isAuthenticated && <button onClick={() => logoutWithRedirect()}>Logout</button>}
        </>
    )
}

export default Login
```

**Comment by pandabrand** [comment]
I've followed the sample more directly, than the example on the auth0 website generator and that seems to have (mostly) fixed the issue. I'm still having a routing issue, but I think that's for the community page.

**Comment by mohammedjok** [comment]
Add discord
