### ISSUE TITLE
Single Page App React.js: outdated auth0-js dependency

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-samples/auth0-react-samples#36]
Seed projects are using outdated auth0-js dependencies:

Latest release auth0-js 8.9.2

![image](https://user-images.githubusercontent.com/26749061/29620214-55fc86de-87eb-11e7-86e1-24e011afd3e5.png)

**Comment by luisrudge** [comment]
we'll upgrade to the latest version: https://github.com/auth0-samples/auth0-react-samples/pull/67
