### ISSUE TITLE
[Best practice] Access auth in nested component.

### ISSUE THREAD

**Issue by NicolasRannou** [auth0-samples/auth0-react-samples#37]
Which would be the best practice to access the `auth` instance in a nested component?

Right now in the demo we pass the `auth` instance to the different pages as a property. I'd like to access the same instance of `auth` in a nested component and propagating the `auth` property down the tree doesn't seem right.

Would it be OK to instance the `auth` element in the `Auth.js` class, do you have a better approach or would it be some kind of anti-pattern?

```
// in Auth.js

// singleton pattern
export let auth = new Auth();

vs

// current export
export default class Auth
```

Thanks!

**Comment by chenkie** [comment]
> propagating the auth property down the tree doesn't seem right
Can you elaborate on this?

**Comment by NicolasRannou** [comment]
Sure - I just think propagating from parent to children is OK but you do not want to propagate a property down 10 children in order for the 10th children to access the property:
```
parent (instanciate auth)
 -> child 0 (prop auth)
    -> child 1 (prop auth)
      -> ...
         -> child 10 (finally uses auth!)
```

I ended up using the singleton pattern in my Auth service and was wondering if there would be a reason not to do it this way.

Will close for now as resolved but please let me know if that seems a bad approach to you!
