### ISSUE TITLE
Router doesn't take component prop

### ISSUE THREAD

**Issue by venil7** [auth0-samples/auth0-react-samples#38]
I believe `<Router/> ` doesn't take `component` as a prop,
those have to be passed in children `<Route>` s

according to https://reacttraining.com/react-router/web/api/BrowserRouter

https://github.com/auth0-samples/auth0-react-samples/blob/ea217004e87728e3eaae3f750ae85431cd4ce2bb/01-Login/src/routes.js#L19

**Comment by luisrudge** [comment]
Fixed in https://github.com/auth0-samples/auth0-react-samples/commit/986a46ea3b419a6d25ae9f8265af92f919f13417

Thanks 🎉
