### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by jeantimex** [auth0-samples/auth0-react-samples#39]
I received this error after login:

"You may have pressed the back button, refreshed during login, opened too many login dialogs, or there is some issue with cookies, since we couldn't find your session. Try logging in again from the application and if the problem persists please contact the administrator."

I cleaned all the browser data including cookies, but cannot get round the error, I use chrome btw, and I have the following set in the allowed callback urls section:
`http://localhost:3000,http://localhost:3000/callback`

did I miss something? Please help, thanks a lot!

<img width="895" alt="screen shot 2017-09-08 at 8 58 14 am" src="https://user-images.githubusercontent.com/565300/30220347-ef1023f0-9473-11e7-9fea-d6e940c0f2cf.png">

**Comment by jeantimex** [comment]
If I sign up a new account, everything works fine, but I don't understand why it happened to the other account.

**Comment by chenkie** [comment]
Does this happen in all browsers? Probably best to contact [support](https://support.auth0.com) for this error.

**Comment by jeantimex** [comment]
Yeah, happened to all browsers.

**Comment by chenkie** [comment]
Ok, best if you contact support.

**Comment by schettino** [comment]
same here! does anyone know how to fix it?

**Comment by thameera** [comment]
@schettino Can you try again and check if there are any error messages in [Logs](https://manage.auth0.com/#/logs)?

**Comment by luisrudge** [comment]
we're now using the hosted login page, so different grant types are not an issue anymore 🎉
