### ISSUE TITLE
`expiresIn` of success login payload does not match Client JWT Expiration setting

### ISSUE THREAD

**Issue by s4291158** [auth0-samples/auth0-react-samples#50]
Following the 01-Login sample I realised `expiresIn` remains 7200 after I've changed the client JWT expiration setting. This change is reflected correctly in the actual jwt token but not in the login success payload.

Am i misinterpreting what `expiresIn` represent?

**Comment by thameera** [comment]
@s4291158 The `expiresIn` parameter here is for the opaque access token you are receiving. The ID token should have the correct expiration after you change it in the client. You can double check this by pasting the ID token at [jwt.io](https://jwt.io) and checking the `iat` and `exp` values.

When you reach the third sample (Calling an API), you can find out how to change the expiration of access token in the API (as opposed to in the client).
