### ISSUE TITLE
03-Calling-an-AP: Request failed with status code 401

### ISSUE THREAD

**Issue by venil7** [auth0-samples/auth0-react-samples#51]
I configured both `auth0-variables.js` and `.env`
I'm getting above error when making private api call

`Insufficient scope`

it works however, if I change this line in server
```
const checkScopes = jwtAuthz(['profile']);
//read:messages - doesnt work
```

**Comment by thameera** [comment]
Hi @venil7, did you configure an API in the dashboard and add the `read:messages` scope as mentioned here? https://github.com/auth0-samples/auth0-react-samples/tree/master/03-Calling-an-API#set-up-a-new-api

**Comment by venil7** [comment]
oh, my bad! should have read the docs properly,
everything is working 👍 ,
closing down this issue
