### ISSUE TITLE
Grant type 'http://auth0.com/oauth/grant-type/password-realm' not allowed for the client.

### ISSUE THREAD

**Issue by alaister** [auth0-samples/auth0-react-samples#54]
Hi,
When I try and login using the embedded login, I get the following error: `Grant type 'http://auth0.com/oauth/grant-type/password-realm' not allowed for the client.`
If I enable the password grant type in my application it works. However I can then disable cross-origin authentication and everything continues to work fine.
Is this an issue with Auth0.js V8 that the upcoming V9 should fix?
Any guidance is much appreciated.

Thanks

**Comment by luisrudge** [comment]
This is now using the hosted login page, so you won't have to handle the grant types at all 🎉
