### ISSUE TITLE
After multiple login attemps, an error show without a message.

### ISSUE THREAD

**Issue by paulioceano** [auth0-samples/auth0-react-samples#60]
After multiple login attemps, an error show without a message.

In the console, the error show:

client.js:800 POST https://paulimar-techaid4.au.auth0.com/usernamepassword/login net::ERR_NETWORK_CHANGED
c._end @ client.js:800
c.end @ client.js:706
i.end @ request-builder.js:58
r.login @ username-password.js:37
r.loginWithCredentials @ redirect.js:66
login @ login?client=7N9Ho9OzTHNGEGsclUBWCW7IJxeUPq0r&protocol=oauth2&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fcallback&response_type=token id_token&scope=openid&audience=https%3A%2F%2Fpaulimar-techaid4.au.auth0.com%2Fuserinfo&nonce=aKTYnDk6kjg7Ct69QVyddRvAy~_5VIIP&auth0Client=eyJuYW1lIjoiYXV0aDAuanMiLCJ2ZXJzaW9uIjoiOC4xMS4zIn0%3D&state=L9pX6--2bLaWxm6P7I31KUbHklLr6Fg6:126

![capture-for-jira-screenshot-20171116-164516-082](https://user-images.githubusercontent.com/15818783/33031376-8136f0ce-cdf4-11e7-89aa-b9f94ef7f162.png)

**Comment by luisrudge** [comment]
ERR_NETWORK_CHANGED is a client error, means that your computer just changed wifi networks
