### ISSUE TITLE
When click "Renewal Token" get an error.

### ISSUE THREAD

**Issue by paulioceano** [auth0-samples/auth0-react-samples#61]
In the 05-renewal-token sample, After I try to get a new token, the console show me a 403 error:

This error is due to a client missmatch. The user has to add http://localhost:3001/silent to the Allowed Callback URL, but the README file doesn't tell this.

After a while, the browser show a message about a timeout error.

**Comment by luisrudge** [comment]
Hi, sorry you hit that bump! I have a PR ready that replaces the `renewAuth` call with `checkSession`. It also has docs on how to setup your client accordingly! https://github.com/auth0-samples/auth0-react-samples/pull/68
