### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by tanakachitsamba** [auth0-samples/auth0-react-samples#65]
any change of having these working on React 16?

**Comment by luisrudge** [comment]
sure. they probably just work with react16. do you want to send a PR upgrading all projects to react 16?

**Comment by corysimmons** [comment]
@luisrudge I haven't tried this out yet, I just saw your other issue suggesting people just bundle 2 versions of React via Yarn resolutions, but I don't want to bundle 2 versions of React just so Lock works with React 16.

Can you, or someone, confirm Lock now works with React 16 w/o Yarn Resolutions?

**Comment by luisrudge** [comment]
Hi, there's more context here: https://github.com/auth0/lock/pull/1142#issuecomment-357694435

TLDR: Lock works with react@16, but you have to use yarn resolutions to bundle a single copy of react.
