### ISSUE TITLE
05-Token-Renewal postMessageOrigin

### ISSUE THREAD

**Issue by murphyke** [auth0-samples/auth0-react-samples#66]
I tried out the token renewal example, and I couldn't get it to work until I changed the [renewAuth call in Auth.js](https://github.com/auth0-samples/auth0-react-samples/blob/master/05-Token-Renewal/src/Auth/Auth.js#L100-L117) to add the option `postMessageOrigin: 'http://localhost:3001'`.

Is that a bug in the sample code, or did I configure something wrong?

**Comment by murphyke** [comment]
I've just discovered that `renewAuth` is deprecated and `checkSession` is the new approach.

**Comment by luisrudge** [comment]
@murphyke I just opened a PR to migrate to checkSession. Check here: https://github.com/auth0-samples/auth0-react-samples/pull/68
