### ISSUE TITLE
Calling Facebook GrapgQl API

### ISSUE THREAD

**Issue by tettusud** [auth0-samples/auth0-react-samples#78]
How can I improve this app to call FB api from this app. I tried to call /v2/user/{user-I’d} unable to get identities.it would be really helpful if you get some working samples

**Comment by jimmyjames** [comment]
Hi @tettusud, if you haven't already, check out the [docs](https://auth0.com/docs/connections/calling-an-external-idp-api) for calling an Identity Provider's (like Facebook) APIs. I don't think this sample would be updated any time soon to demonstrate calling IdP APIs, so going to close this issue. But if you're still interested in seeing a sample that does demonstrate this, please provide input [here](https://auth0.com/feedback) - reported requests are looked at there by our Product Management team. Thanks!
