### ISSUE TITLE
Synchronous parsehash

### ISSUE THREAD

**Issue by samudurand** [auth0-samples/auth0-react-samples#85]
I am using React and trying to use the `auth0.parseHash` method in combination with the React-router. My problem is that this method is asynchronous and works by callback. The react router cannot handle promises or that kind of callback as far as I could see. Which mean that I am having issues to use the usual `<Redirect>` component to redirect the user depending on the result of the hash extraction... 

Considering that this is not calling any outside resource but simple reading the hash why is it a method with callback instead of a synchronous method ? Is there a way I missed to make this work with the Router ? Beside manually forcing a redirect one the processing is finished ? That process is very quick and I don't see why it should be treated as asynchronous. Maybe I am just missing something in the React or Oauth philosophy/process ?

**Comment by upanshed** [comment]
Im having the same issue, did you find a solution?

**Comment by samudurand** [comment]
@upanshed I changed my code to do a manual redirect instead , you can do that by getting the router directly from the Router directive and passing that to the authentication method

```
 <Route path="/callback" render={({history}) => {
                auth.extractAndSaveUserToken(() => {
                   history.push("/");
                }, () => {
                  history.push("/authError");
                });
                return (<div>Loading</div>);
              }} />

```

**Comment by lukeoliff** [comment]
Hey @samudurand sorry for being late to this!

I addressed this exactly recently in a demo app. Check out this: I provide some state aware functions to be used as callbacks in my auth utility class. Ideally, our SDKs will be updated to support Promises. :)

https://github.com/lukeoliff/auth0-react-material/blob/master/www-client/src/components/App.js

**Comment by samudurand** [comment]
@lukeoliff looks good ! however I am still wondering why it is not synchronous ? As far as I know this does not require any external http call ? So why bother with asynchronous ?

**Comment by jimmyjames** [comment]
Closing this issue  since we've just recently made some significant changes to this sample and Quickstart, utilizing the new `auth0-spa-js` SDK. If you continue to experience this issue or any others, don't hesitate to create a new issue. Thanks!

References:
- [Updated React Quickstart](https://auth0.com/docs/quickstart/spa/react)
- [auth0-spa-js SDK](https://github.com/auth0/auth0-spa-js)
