### ISSUE TITLE
Switching accounts

### ISSUE THREAD

**Issue by joshgeller** [auth0-samples/auth0-react-samples#97]
Apologies if this is not the forum for support questions. I am trying to 1) log into a user account, 2) log out, 3) log in with a different user account.

Step 1 and 2 work as expected, but when I click "log in" again, I am simply logged into the same account from step 1. I do not see the login form where I would be able to enter credentials for a different account.

Is this expected behavior? How can I prompt the login form to show if there is no current active session?

Thanks.

**Comment by jimmyjames** [comment]
Fixed with https://github.com/auth0-samples/auth0-react-samples/pull/108
